### ISSUE TITLE
armv7l arch

### ISSUE THREAD

**Issue by mapagm** [Screetsec/TheFatRat#101]
I can't install TheFatRat on Kali Linux ARM version (Raspberry Pi 3). My Kali Linux:

`Linux kali 4.4.50-v7 #1 SMP Fri Apr 21 01:18:29 CDT 2017 armv7l GNU/Linux`

During instalation TheFatRat there is an error:

```
Setup Script for FATRAT 1.9       

Setup will not proceed because none of these archs were detected

x86_64|i386|i486|i586|i686

Report this arch:  armv7l  into fatrat issues on github
```

Funny thing is that i could install TheFatRat on Kali ARM a week ago...

**Comment by peterpt** [comment]
write ./update to get latest setup script from fatrat and execute ./setup.sh .

**Comment by mapagm** [comment]
It works ;)

**Comment by dariking** [comment]
Como actualizar armv81

**Comment by Kp691** [comment]
I tried ./update but still getting the issue

**Comment by shaheem007** [comment]
Updating Fatrat from Github  **
 ************************************
HEAD is now at 3abb034 update
From https://github.com/Screetsec/TheFatRat
 * branch            master     -> FETCH_HEAD                 Already up to date.
 *************************
 **   Update Completed  **
 *************************
root@localhost:~/TheFatRat# uname -m
armv7l
root@localhost:~/TheFatRat# git pull
Already up to date.

**Comment by shaheem007** [comment]
[ * ] Fixing any possible broken packages in apt management

./setup.sh: line 1125: sudo: command not found

 [ ✔ ] Done ! ....Proceeding with setup

**Comment by shaheem007** [comment]
i fixed it

**Comment by Moqzekun** [comment]
👌


 
---Original---

**Comment by shaheem007** [comment]
but fatrat dont work

**Comment by shaheem007** [comment]
im runing armv7l

**Comment by BaRRaKudaRain** [comment]
What?! Sudo not found?

--
---------------------------
An outsider, the BaRRaKudaRain

-----Original Message-----

**Comment by peterpt** [comment]
Arm architectures are no available in fatrat for multiple reasons that i wrote before here :

- Arm does not have a strong processor and memory to run fatrat (because fatrat runs metasploit framework . gcc and other tools that require cpu and memory when they are running with fatrat .

- Some packages are not in Arm linux OS or may give issues installing .  

- other stuff i cant remember now , witch one of them is that i dont want to spend my own life here solving your fatrat issues in your arm broken device .
