### ISSUE TITLE
TheFatRat

### ISSUE THREAD

**Issue by fostrok1** [Screetsec/TheFatRat#104]
As i can do to update thefatrat setup folder, because at the moment od installing the setup.sh at the end it tells me that there was a problem installing dex2jar on your system, aborted. What can i do to solve it and everything will be fine. Thanks!

**Comment by peterpt** [comment]
write in your terminal this comand : 
ls /usr/local/sbin/d2j*

and put here the output

**Comment by fostrok1** [comment]
I now see these red letters in the right window

2017-05-06 23:49 GMT-06:00 peterpt <notifications@github.com>:

**Comment by peterpt** [comment]
what does that suppose to mean ?!!!!
Learn how to get a print screen and post it here .

**Comment by fostrok1** [comment]
this pops up: configuration file does not exists, run setup.sh first for
confing...

2017-05-07 17:04 GMT-06:00 peterpt <notifications@github.com>:

**Comment by peterpt** [comment]
configuration file is created when you run setup.sh , every package must be installed successfully or fatrat does not work .
I will not waste my time here in this issue anymore until you provide the information i ask you .
There are multipe factors that can influence an error , and to know which thing did not worked then you must provide me the information i asked .
So , again .
You told dex2jar was not installing , and i told you to write on your terminal : 
ls /usr/local/sbin/d2j*

install shutter (apt-get install shutter) to get your print screens .

**Comment by fostrok1** [comment]
The version that asks me to install dex2jar was version 2016.2 and I have
uninstalled it. I installed the 2017.1 version of kali linux. Now let's
start with zero, please.


2017-05-07 17:50 GMT-06:00 peterpt <notifications@github.com>:

**Comment by fostrok1** [comment]
firstneror

2017-05-07 20:26 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
second error

2017-05-07 22:13 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
After updating repositories and packages, decides to try again to install
thefatrat. I gave the following error!

2017-05-07 22:13 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
After the third error install the command that sent me: ls / usr / local /
sbin / d2j *. And I solved now only with this!

2017-05-07 23:17 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
I'm where I'm at, please help me if ... I do not know what to do !!!



2017-05-07 23:19 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by peterpt** [comment]
What is your native language ?

**Comment by fostrok1** [comment]
Spanish

2017-05-08 0:45 GMT-06:00 peterpt <notifications@github.com>:

**Comment by fostrok1** [comment]
What can i do with that last mistake

2017-05-08 14:39 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by peterpt** [comment]
by your email i tough you were Brasilian or Portuguese , those languages i can speak .
Anyway .

1st of all  : 
- learn how to take a screenshot in linux : http://www.thegeekstuff.com/2012/08/screenshot-ubuntu

2nd : 
- Open the terminal .
write : ls /usr/local/sbin/d2j*

then take a print screen and post here .

**Comment by fostrok1** [comment]
2017-05-08 23:53 GMT-06:00 peterpt <notifications@github.com>:

**Comment by fostrok1** [comment]
Now what happens next

2017-05-09 8:28 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by godimdhruv** [comment]
don't email him take the screenshot upload here

**Comment by fostrok1** [comment]
I do not understand that you want the screenshot ... if you can make a
video and send to understand better. Thank you

2017-05-09 9:58 GMT-06:00 godimdhruv <notifications@github.com>:

**Comment by fostrok1** [comment]
/root/calc.png

2017-05-08 23:53 GMT-06:00 peterpt <notifications@github.com>:

**Comment by fostrok1** [comment]
I'm new to linux. Help me by making a short video of what they ask me


2017-05-09 13:14 GMT-06:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by peterpt** [comment]
write in your terminal : 
apt-get install dex2jar -y

the execute setup.sh from fatrat and everything will be fine .

**Comment by fostrok1** [comment]
/root/calc.png

2017-05-10 9:05 GMT+02:00 peterpt <notifications@github.com>:

**Comment by fostrok1** [comment]
2017-05-12 9:42 GMT+02:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
help me please

2017-05-12 9:43 GMT+02:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
You ask me to install dex2jar 2.0 and get an error [X] Aapt
...........................
./setup.sh: line 502: /root/TheFatRat/setup/logs/setup.log: There is no
file or directory

What I can do...


2017-05-12 9:43 GMT+02:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by peterpt** [comment]
don't mess up with script code and then post here as an issue .
It is impossible for that error appear in setup script by the fact that almost all errors are omitted to null , and those that are not just simply popup an error message explaining what happened .
I don't even gonna give my self the trouble to explain how logs are created because it will be a waste of text here .

Many of you here want fatrat to work on every device with linux OS that you may have , but the fact is that we tested only on desktop environments and not on android devices .
So , you all popup issues here from those devices that we have to figure out why they are happening even if we have no chance to test them here .
We will release the new fatrat probably in next week (if i get time here to finish it) , on next version of fatrat , if setup script says that was not possible to install something , then fatrat will not run on that specific device architecture .
And if you really want to put it to work , then you better look up on the web how to compile that specific package manually on your device , because we will not waste our time on teaching people how to work with linux .
You and everyone should know that if by default your apt already dependencies unresolved by some package on your OS , then you first must fix your OS issues before even trying to install fatrat on it .

before installing fatrat everyone should do and update , upgrade and an apt install fix to see if apt on your OS pops up any dependencies unresolved , and then if everything is fine with your apt installation manager , then proceed with fatrat installation .

Most issues on this git exists because the user was testing installations of other stuff in his OS and break up the normal apt procedure installation .
That lead to apt unresolved issues , and since user was not able to fix the issues then try to install fatrat , of course that fatrat will not make any miracles to your broken apt .

I have an arm7 device , but i never tested fatrat there , with 1.9.4 version i will test it there , and if i start get incompatibility issues  then we will probably remove arm and armel support from fatrat to avoid headaches .

Note : use google translation .

**Comment by fostrok1** [comment]
Friend I think he had a bad day, but now I help him with that> there was a
cake in front of a statue of Jesus Christ and I started to say your dad
does not exist your pope does not exits. There was a religious back and
forth to pray God send a storm with lightning and thunder to this man so
that he repents and the storm came with lightning and thunder and lightning
to strike the pair, the bolt screamed aaaaerrrrrgggg almost. Well he
stopped and he told the statue your dad exists but he looks like he does
not have a mark, I do not hit any jajajajjajajaj

2017-05-12 10:18 GMT+02:00 peterpt <notifications@github.com>:

**Comment by fostrok1** [comment]
Already resolved the updates, but not the dex2jar 2.0.
I have given you the command>

Apt-get install dex2jar -y

It tells me that it is already in its most recent version, but it still
appears to me that>

[*] Manually Installing Dex2Jar 2.0

There was an issue installing dex2jar in your system, aborting.

  What I can do ? Please. Understand me a little, I'm new to this. I want
and I really want to learn ...

2017-05-12 17:48 GMT+02:00 Erick J Flores <estilopropio004@gmail.com>:

**Comment by fostrok1** [comment]
2017-05-12 17:52 GMT+02:00 Erick J Flores <estilopropio004@gmail.com>:
