### ISSUE TITLE
TheFatRat

### ISSUE THREAD

**Issue by fostrok2** [Screetsec/TheFatRat#112]
I can not use the user manual that I have to manually install dex2jar 2.0. You can tell me that I have a download from a source or something else. Thank you

**Comment by peterpt** [comment]
Look , i already told you before what do i need to diagnose that error .
I need you to search on the web how to make a print screen from your device .
Then i need you to write on your terminal ( ls /usr/local/sbin/d2j* ) and you should get a print screen of that output .
I need to know if setup copied to that folder the d2j* files that setup is programmed to do .

1ST , i need you to look for that , and then depending on the result there i will proceed to a different way to try to diagnose why your system can not find the files .

You created a new issue with the same error , i notice that , but that will not resolve your problem if you continue to write here the same things and not giving me what i need , so i can be able to fix your device problem .

One thing very important on the web is to understand English , English is the universal language , if you do not understand english then you will not be able to understand what i ask you to do .

**Comment by fostrok2** [comment]
I want to give you what you ask ... but I need you to confirm me if this
screenshot serves you?

2017-05-13 8:29 GMT+02:00 peterpt <notifications@github.com>:

**Comment by peterpt** [comment]
"but I need you to confirm me if this screenshot serves you?"

what screenshot ?
where it is ?

next one i will close this issue .

**Comment by fostrok2** [comment]
Thank you for not wanting to help or DO NOT KNOW WHAT TO DO

2017-05-14 3:35 GMT-06:00 peterpt <notifications@github.com>:

**Comment by fostrok2** [comment]
There is no one else who wants to help me ... Because I sent you the
screenshot that you piste obviously do not want to help me


2017-05-14 13:20 GMT-06:00 Erick Josue Flores Motiño <
bordadospoint@gmail.com>:

**Comment by fostrok2** [comment]
puta gracias por tu madures


2017-05-14 14:59 GMT-06:00 peterpt <notifications@github.com>:

**Comment by peterpt** [comment]
Eventually in 4 or 5 years if you continue to use linux and watching other issues , you will realize that my email is not notifications@github.com , and that exists on the reply field an option to upload files directly to github , like the screenshots i asked you .
Due to your last reply , and because i understand a little bit of spanish (not enough to establish a conversation) , i will lock this thread due your lack of education .
This issue was not solved because the user was unable to provide the correct or any information i asked him to do .
User started a different issue with the same subject where in his previous issue i pointed him to specific links that teach him how to make a screenshot .
https://github.com/Screetsec/TheFatRat/issues/104
This topic will be locked from now on .
