### ISSUE TITLE
Failed to run dx on proguard processed jar file

### ISSUE THREAD

**Issue by ethiccode** [Screetsec/TheFatRat#113]
PLEASE HELP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
error whlile Backdooring Original apk 
![screenshot from 2017-05-20 02-22-44](https://cloud.githubusercontent.com/assets/28811396/26266032/495c7782-3d03-11e7-997e-834946643919.png)
and another error using old fatrat methord
![screenshot from 2017-05-20 02-25-42](https://cloud.githubusercontent.com/assets/28811396/26266108/a8a85418-3d03-11e7-8cd3-12bc0319fd6d.png)

**Comment by peterpt** [comment]
On the first screenshot (from backdoor-apk 0.2.2) i advise you to wait for the next fatrat release , it will be very soon .
on the second screenshot (old fatrat method) install nokogiri .
1st - open terminal
2nd - write the command "gem install nokogiri"

**Comment by ethiccode** [comment]
thanks i fixed the (old fatrat methord) yesterday .
but why should i wait for next fatrat release?
 I am getiing this error aslo in (backdoor-apk). you mean i should also wait aslo for (backdoor-apk) to release new version?
![screenshot from 2017-05-20 17-33-49](https://cloud.githubusercontent.com/assets/28811396/26275528/9be80eba-3d82-11e7-833f-c4eb8d8ea62d.png)

**Comment by peterpt** [comment]
Some apks are build ed with new mechanisms that backdoor-apk is not yet able solve .
My advice to you is to try another apk in fatrat (backdoor-factory) to see if the error appears again .
If the error does not popup then is because the first apk you used is not yet compatible with backdoor-factory , otherwise it could be a generic error .

We don't write backdoor-factory , backdoor factory does not belong to fatrat , that tool was implemented in fatrat from dana-at-cp git repository , we just added his tool to fatrat .
When Dana update again his github with considerable changes , then we will update also the backdoor-apk in fatrat .

You should create an issue from that apk in backdoor factory github , so dana can give a look at it , he is the main developer of that tool .

**Comment by ethiccode** [comment]
ohh! i got this i have alredy issued a problem there too.

**Comment by peterpt** [comment]
My advice to you is to upload the apk file you are trying to make a rat into backdoor-apk dana travis github .
Without your apk he is unable to check out why that error pops up .
rename your apk to zip and upload it to dana github repository where you created your issue , and tell him to rename the zip to apk when he downloads it .
You can upload using github interface bellow the reply text box .

**Comment by gangaanonymous** [comment]
Whatever apk i choose it always come with unable to run dx On proguard in backdoot apk ....How to fix it...Plz help

**Comment by peterpt** [comment]
Who told you that backdoor_apk would work on every apk you want to put a rat on it ?
You have 2 choices : 

1st - build your rat with old apk build method

2nd - Contact google to they don`t write the new apks differently than the old ones , so you can put a rat on them .

If you want just to build a rat apk file to test yourself then use msfvenom (android) .
It will build a rat apk for you to test on your devices .
