### ISSUE TITLE
Apktool & Dex2jar installation issues

### ISSUE THREAD

**Issue by vwadhwa3** [Screetsec/TheFatRat#123]
i was not able install 
Apktool -> Not OK
Dex2Jar -> Not OK

please help

**Comment by peterpt** [comment]
give me the output of these commands : 
1st -  find /usr/local/sbin -name apktool

2nd - ls /usr/local/sbin/d2j-*

3rd - cd /usr/local/share/dex2jar/bin && ls

get print screens from those outputs and post here .
If you do not know how to even make a print screen or create an output to show me these results then i will close this issue .
It could not be your case , but i lost my patience to deal with issues posted by people that just installed linux for the first time just to use fatrat , which means they do not have any experience in linux , and this is not acceptable and make me loose a lot of my precious time .

**Comment by peterpt** [comment]
Clone again the fatrat git , or write ./update in fatrat folder and then execute ./setup.sh again .

I notice a bug in dex2jar installation code that was disabling the possibility of installation of that tool .
In apktool i did not notice any issue in the code , however on of the problems that may be happening is that you may have in your /usr/bin or /usr/sbin or /usr/local/bin a filename called apktool , if this is the case then when the script calls apktool it finds another version (the one you may have) , then the script creates a symlink in your /usr/local/sbin directory called "apktool" this symlink will reedirect to fatrat directory where apktool is , but while another apktool file exists in those previous directories i wrote before then they will pop up first because those directories have higher permission than /usr/local/sbin

In linux when you call some file in terminal , the order of the system to look for that file will be these order directories : 

1st - /bin
2nd - /sbin
3rd - /usr/bin
4th - /usr/sbin
5th - /usr/local/bin
6th - /usr/local/sbin

if you install a file in /usr/local/sbin (like we do in fatrat) , and exists another file with same name in previous directories , then the system will give priority to the first directories , and if the file is not found in any of those directories then will go to last one (6th) .

For those that have this problem with apktool , best solution is to delete any file with that name from directory 1st to 6th , and then run setup.sh .

I hope this explanation gives you and all others that read this reply a clear view why that problem may occur .

This is why we prepared the setup script before install some tool , check if that tool exists .
In case of apktool the script will look for the apktool version , we did this way because kali repository still have an old version , and this old version pops up problems on the creation of the apk rat files , this way we uninstall that version and we instruct setup script to  create a symlink (shortcut) to latest apktool in fatrat directory .

**Comment by Konhumy** [comment]
Installation stucking on dex2jar.
Plz Help peterpt .

**Comment by peterpt** [comment]
open a terminal and write these commands : 
ls /usr/local/sbin/d2j-*
ls /usr/local/share/dex2jar/bin/*

then get a print screen like you see in the 2nd post here and upload it here .
Note : There is on issues in fatrat git a topic that explains you how to get a print screen and upload it to github .
