### ISSUE TITLE
I can't get monodevelop to work

### ISSUE THREAD

**Issue by NikkiRikota** [Screetsec/TheFatRat#125]
I've tried so many times to install The Fat Rat, but it still failing since it can't install Monodevelop. I've tried and tried but I think I must be missing something. 
Please someone help me. 
I've already tried these commands:
apt-get remove --purge monodevelop && apt-get autoremove && apt-get install -f
./update
chmod +x setup.sh

This is my Kali Linux
Linux KaliNikki 4.9.0-kali3-686-pae #1 SMP Debian 4.9.18-1kali1 (2017-04-04) i686 GNU/Linux

**Comment by peterpt** [comment]
write in your terminal : apt-get install monodevelop and take a print screen from the output and post it here .
here it is how you can take a print screen : 
https://youtu.be/mGXFVxDlWgU

**Comment by NikkiRikota** [comment]
![screenshot from 2017-06-01 07-18-40](https://cloud.githubusercontent.com/assets/29028281/26675465/1502f81a-4692-11e7-858b-47ff5f48ba46.png)

**Comment by peterpt** [comment]
do this on your terminal : 
cat /etc/apt/sources.list

and post here the output

**Comment by peterpt** [comment]
Well , i will close this issue .
It looks to me that you recently installed kali linux and your sources.list file is not filled with kali repositories correctly .
with leafpad open the file in /etc/ap/sources.list and add these next lines to that file : 

deb http://old.kali.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free

after that save the file .
Then run "apt-get update" in terminal
and finally run again setup.sh from fatrat .

You can have sana repositories and roolling together on same file because apt package management will get the latest version by default , and it will be rolling repositories .
In case some package is not yet in rolling repositories then apt will pick it from Sana repo .

Both Sana & Rolling are debian jessie forks  , so there will not be incompatibilities .

**Comment by NikkiRikota** [comment]
I still can't make it work. I've copy those lines were you told me to, but It still turn out the same.
![screenshot from 2017-06-01 19-13-04](https://cloud.githubusercontent.com/assets/29028281/26703092/fdceeb7c-46f5-11e7-8e50-99d5809ed3b2.png)

**Comment by NikkiRikota** [comment]
![screenshot from 2017-06-01 19-16-58](https://cloud.githubusercontent.com/assets/29028281/26703162/4683fb50-46f6-11e7-8d23-562102421b84.png)

**Comment by peterpt** [comment]
take out the # before the links in sources.list .
If you leave a # behind then that line will be ignored .

**Comment by NikkiRikota** [comment]
Thanks. I'm downloading it right now. I'll see what happens when it finishes, but I hope it works. Thanks again!

**Comment by NikkiRikota** [comment]
Thank you Man. That was really helpful!

**Comment by TheSuperXD** [comment]
I cant downoad the fatrat who can help me?

**Comment by ananthram252** [comment]
every time i try to install fatrat..its always showing me monodevelop and Mingw-w64 was not found

**Comment by bhawanijangid** [comment]
hey as per all comments or commands i used everything but still having problem with monodevelop, i used these commands and i m done
but here i m giving u final solution (official from https://www.monodevelop.com/download/#fndtn-download-lin-ubuntu)
sudo apt install apt-transport-https dirmngr
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb https://download.mono-project.com/repo/ubuntu vs-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-vs.list
sudo apt update

**Comment by peterpt** [comment]
look , fatrat only needs mono-mcs and mono-devel packages , you are running an old version , clone again the fatrat git .
