### ISSUE TITLE
Monodevelop installation issues .

### ISSUE THREAD

**Issue by Elements01** [Screetsec/TheFatRat#126]
Hi,

i have a problem installing monodevelop if i ran setup.sh it says installing monodevelop but it`s not installing it.
how can i fix it?

thanks

**Comment by peterpt** [comment]
write in your terminal : uname -a
and then : apt-get install monodevelop

get a print screen and post it here
to know  how to do a print screen watch this video : 
https://www.youtube.com/watch?v=mGXFVxDlWgU

I also want to know what is your linux distribution , kali , debian , ubuntu , etc ....

By default monodevelop is in every linux distro , i made a test with a clean install of fatrat 1.9.4 and everything went perfectly .
https://www.youtube.com/watch?v=xdI6Y7WZyj8

**Comment by Elements01** [comment]
my distribution is Kali 
here is a screenshot 
http://imgur.com/a/OY0ba

**Comment by peterpt** [comment]
write in your terminal : 
cat /etc/apt/sources.list

get a print screen and post it here

**Comment by peterpt** [comment]
Write on the terminal
cat /etc/apt/sources.list

post here a screenshot

**Comment by Elements01** [comment]
here is the screenshot
![kali1](https://cloud.githubusercontent.com/assets/25932138/26701584/fbf48ff6-4721-11e7-8555-0484ab76405b.png)

**Comment by peterpt** [comment]
well , it looks that you do not have in your sources.list any repository from kali .
open this file with any text editor : sources.list in the folder /etc/apt

add these lines to the beginning : 

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb http://old.kali.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib

save the file and then write this in your terminal : 
apt-get update && apt-get upgrade

then run setup of fatrat again .

This issue you have is not related to fatrat .

**Comment by Elements01** [comment]
thanks a lot it works now

**Comment by gasparkali123** [comment]
thanks, i was install the fat rat

**Comment by 1Jayso** [comment]
I installed mono develop on parrot linux but when I check my installed apps I only see the  documentation, how do I configure it so I can use the app?

**Comment by peterpt** [comment]
look , we do not give support to Linux OS systems issues , the problem you have and 90% else have here is that you like to mess up with linux , then you broke your linux packages , and then you all come here saying that you are unable to install something and the problem is our script ,when in reality is the lack of knowledge in linux a lot of bad testing while trying to fix something .
Let me be clear with you and everywhere else with the same issues that are not related to fatrat script : 
We do not give support for Linux OS problems .

We are already doing to much when we tell users to do this or that to fix something , because in fact we should be worried only if user gets any problem executing some command on the fatrat and some bug appear .

I will lock this and every other issue , so people dont start to write on closed issues .
In mean while , for you the solution is to completly remove monodenvelop and execute setup script again .

execute in terminal : 
apt-get remove --purge monodevelop -y && apt-get autoremove && apt-get install -f

Then after this , execute setup script from fatrat and it will install monodevelop properly
