### ISSUE TITLE
Keylogger and persistance function?

### ISSUE THREAD

**Issue by kevilex** [Screetsec/TheFatRat#141]
Would love these functions to be there, thanks.

**Comment by peterpt** [comment]
What you are asking is the something as having a backdoor on the victim at windows/linux startup so it connects to you every time the victim starts its windows/linux .
I do not think we will develop that option because that way the new rats will be detected more often on antivirus , and eventually with continuous windows development the exe will probably break and windows will popup errors at user windows startup .

Fatrat in my point of view , provides only a way for you to access victims machine when the victim str«arts up your rat .
For a key-logger , a background service must be active to catch victim inputs on keyboard , and this will lead to the first part of this comment .

In my point of view , fatrat is only a penetration test tool .

I have no idea what Edo thinks about that , but from my side you already know what to expect .
If something like you asked one day appears in fatrat  , then you can be sure that was not made with my code .
