### ISSUE TITLE
Unable to perform installation - recommends to update package

### ISSUE THREAD

**Issue by Bomber22** [Screetsec/TheFatRat#142]
![image](https://user-images.githubusercontent.com/29372651/27029348-8c68564c-4f85-11e7-8e0b-866054e92a95.png)

![image](https://user-images.githubusercontent.com/29372651/27029331-7e30ff3e-4f85-11e7-80c3-87f125281c63.png)

![image](https://user-images.githubusercontent.com/29372651/27029132-b10f3d86-4f84-11e7-9b87-4b3d0431f1a2.png)

Please see the screenshot. the 1st is soon after i ran the setup and then it prompted to install the backdoor package either manually or from kali repository, i tried option 2 and it went thru some series of links and then ended up at screenshot 3 where it suggests to update the package, i am not able to proceed with installation :( :( .. please assist. 

Also, when i tried to update the backdoor package manually, it asks for backdoor.py and also searchsploit. which is not available in the package. i checked every folder from the fatrat package. however i used the backdoor.py and searchsploit default from the OS. 

![image](https://user-images.githubusercontent.com/29372651/27029637-cb742ae0-4f86-11e7-8251-311c6e166904.png)

end result is to try apt-get remove --purge <packagename> && apt-get autoremove && apt-get ins

![image](https://user-images.githubusercontent.com/29372651/27030589-805b2c62-4f8a-11e7-9b28-552cd9c35580.png)

i tried the same in kali, same error. i even updated and upgrade the OS.

thank you..

**Comment by peterpt** [comment]
damn !!! that is old school stuff , my first installation linux OS was backtrack .

I am curious to know which sources do you have in sources.list .

By the way , do not interrupt fatrat setup in the middle with CTRL+C specially  after metasploit detection and others ahead , that will change your current repositories .

* Point 1 : monodevelop issue
- monodevelop issue can happen if you do not have any repositories in your sources.list .
- can also happens if you already try to install monodevelop before without success
- can also happen if your linux OS is so old that for monodevelop install you will need to upgrade your linux to a more recent version due incompatible libraries between monodevelop and your old libraries from your current OS .

If you want to stick with backtrack , then you must compile monodevelope from source code , and even by that way i believe you will have some difficulties .

* Aapt issue
- i have no idea , but the file that aapt is looking exists in android-sdk folder : 
https://github.com/Screetsec/TheFatRat/tree/master/tools/android-sdk/lib64

My advice to you is to install a more recent linux OS , in case you want to stick in sys V init , then you can get kali wheezy (pentest) , or a more recent version which is Devuan linux OS (not pentest) , but you can install the tools you need manually  .
I case you dont care about systemd and do not mind have it in your linux OS , then install kali rooling or debian 8 or 9 .

In any new installation before you will need to fill your sources.list with your linux os repositories .
By default , people think that when they install a linux OS then the sources.list already have that linux OS repositories written there , that is not true .
Google your Linux OS codename repository list on the web and write the links in sources.list .

I will not do that job for you .

**Comment by Bomber22** [comment]
hi peter.. thanks a lot for your assistance it worked on kali roller!!
