### ISSUE TITLE
How to uninstall FatRat ? I wanna install the latest one

### ISSUE THREAD

**Issue by hyzo90** [Screetsec/TheFatRat#152]
Hi , 
I'm trying to uninstall FatRat but have no idea how. 
I wanna install the latest one. I tried to update to the latest one but still not up to the latest one.

Kindly need your help to do this.

Thank you

**Comment by peterpt** [comment]
One of the issues why fatrat is not updating correctly is because fatrat creates new files on execution , and when an update is called then the git compares your fatrat directory structure with the remote git , and will find files that do not belong to the original git .

If you write on your terminal folder under fatrat directory these commands : 

rm config/*
rm config/listeners/*
rm backdoored/output/*
rm logs/*
rm output/*
rm temp/*
./update && ./setup.sh

then fatrat will update to latest version

**Comment by amitjalwanshi16** [comment]
Hi I am trying to uninstall it and install the fresh version is there any command for this.
