### ISSUE TITLE
There was an error creating your FUD rat with Powerstager .

### ISSUE THREAD

**Issue by mateo24xx** [Screetsec/TheFatRat#163]
i tried everything to resolve this but can find the solution 
i installed mingw w32 and 64 ..
but i see that when i do setup.sh i have some files there is no found beside the files name .
example :  Aapt..................(empty)
                 apktool............(empty)
                 dexjar...............(empty)
and 2others,
is there a way to fix this thanks

**Comment by peterpt** [comment]
we need 3 files from your logd folder in fatrat .
Install.log
setup.log
fudwin.log <- in case exists

**Comment by hazempgm** [comment]
I've got the same problem ! but what seems to trigger it for me is typing my ddns instead of public ip .
Is there any way to use ddns in fatrat FUD instead of my ip ?

**Comment by mateo24xx** [comment]
still dont now how to resolve this .;can someone please help ??
i stuck with this error and try to resolve this for months now and dont find any answer on the net and the fatrat creator really dont want to help !!

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/issues/124

**Comment by mateo24xx** [comment]
sorry to say this but why a screenshot ???
 dont be so desoblegeant..everything is in the title 
"" There was an error creating your FUD rat with Powerstager ""
there is a problem with fatrat you are the creator so help us to fix this

**Comment by mateo24xx** [comment]
solved thanks

**Comment by peterpt** [comment]
Don`t be ridiculous , do you think i am clairvoyant .
Fatrat in a normal and maintained linux system works without any issues .
Sometimes , only sometimes , some bug that we missed may appear , but 90% of the issues here are related to bad user maintenance in his linux distribution , which means that these 90% of the issues are related to fatrat needed packages installation .
By this i mean when user is running the setup .
Since my copy of fatrat is working without any issue , and it is the same copy you cloned from git , i can not guess why powerstager gave you an issue .
By default powerstager creates a log on every use , which is stored in "logs" folder inside fatrat folder .
when you get an error with powerstager , i must know what caused that error .

An example created by yourself : 
https://github.com/Screetsec/TheFatRat/issues/182

On this example you gave us the info we need to understand the cause of your issue , but on this one i am writing you did not gave anything , and you are expecting that we already know what is the cause
of the problem . We do not know and that is why we ask for screenshots of info from the logs , so we can understand the cause of the problem .

**Comment by Nigrini** [comment]
I did a clean Kali 2018.4 install.
update and upgrade the system
Installed wine
Installed Mingw-w64
Installed TheFatRat

Everything installed without errors, and where needed TheFatRat installed the missing software.

However when I pick option 2 to create a FUD with Powerstager I get the error "There was an error creating your FUD rat with Powerstager"

I have no idea what is the reason for the error, or where to start looking for a solution

**Comment by peterpt** [comment]
If you start read this issue on here from the beginning you will know what we need to identify the problem .

**Comment by Nigrini** [comment]
Sorry, my bad.

I manage to fix this quite easily. Thank you for a great tool !

**Comment by hdawg12** [comment]
> If you start read this issue on here from the beginning you will know what we need to identify the problem .

here is the log that produced the error for powerstager
[fudwin.log](https://github.com/Screetsec/TheFatRat/files/4618392/fudwin.log)

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
