### ISSUE TITLE
Decompiling APK takes forever

### ISSUE THREAD

**Issue by gufkl** [Screetsec/TheFatRat#175]
Hi,thx for make awesome tools :)
I have a problem while embedd paylod to original apk
The decompiling process takes forever,about half hour and not finish 
i tried the method "1" & "old fatrat method"
But the result is same,loooong wait and even not finish
I use kali linux 2017.1 on raspberry pi 3
I know the rpi3 not fast,but but it should not be that long,i guess?
Sorry for my bad english

**Comment by sasatefa2009** [comment]
just a small request, can you try with another apk ? maybe a 2 Megabyte app or anything.

**Comment by sasatefa2009** [comment]
i've found that many dependencies were not installed so i did
and here they are, try installing this

gem install bundler
gem install pristine
gem install bcrypt
gem install bcrypt_pbkdf
gem install msgpack
gem install network_interface
gem install pcaprub
gem install pg
gem install pg_array_parser
gem install rbnacl-libsodium
gem install redcarpet
gem install sqlite3
gem install rake
sudo apt-get install postgresql postgresql-contrib libpq-dev python-dev postgis
sudo apt install python3-dev python3-psycopg2
pip install psycopg2

but i still have this error, its produced by TheFatRat old method

```
/usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `map!'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/definition.rb:159:in `specs'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/definition.rb:218:in `specs_for'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/definition.rb:207:in `requested_specs'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:109:in `block in definition_method'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/runtime.rb:21:in `setup'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
	from /usr/local/rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/share/metasploit-framework/config/boot.rb:26:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/metasploit-framework/lib/msfenv.rb:12:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/bin/msfvenom:10:in `<main>'

```

**Comment by peterpt** [comment]
none of the gems installed make ruby script in fatrat work .
I am still figuring out where or who gave you that idea to install those gems for ruby script .
Understand now and forever and learn .

To know which gems are needed to be installed in a specific ruby script , all you have to do is to look into the first lines of that script and watch the parameter "require" .
If you look here https://github.com/Screetsec/TheFatRat/blob/master/tools/apkembed.rb at lines 10 , 11 and 12 , you will see that old apk script only requires : 

require 'nokogiri'
require 'fileutils'
require 'optparse'

this way you only need to install : 

gem install nokogiri
gem install fileutils
gem install optparse

and the script should run without any errors of missing libraries .

**Comment by sasatefa2009** [comment]
@peterpt 
Well, first of all I'm not inventing ruby libraries. they were in the error file reported by TheFatRat at the first time, it throws this missing libraries to me.

secondly, i already have nokogiri and i installed it again.
also fileutils throws an error like in this thread (https://stackoverflow.com/questions/43988796/does-fileutils-require-an-unavailable-ruby-version)
or maybe do you mean " file-utils "
also there is nothing as optparse, there is " OptionParser " and " rubysl-optparse ", so which one do you mean ?

and please don't close any issue before the problem is solved.

**Comment by peterpt** [comment]
Your ruby is messed up , and i say this because you are the first person reporting this error , and this means that something is not right in your system config .
what is the name of your linux dristribution ?

uname -a

fatrat original ruby script is from this git : 
https://gist.github.com/SkullTech/a62d106b55562cc1ab88

"gem install fileutils "should be enough , however new versions of ruby may not work with gems from previous versions .

**Comment by peterpt** [comment]
for optparse use : gem install OptionParser
for file-utils use : gem install file-utils
for nokogiri use : gem install nokogiri

**Comment by sasatefa2009** [comment]
@peterpt 

> Linux kali 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux

gem install fileutils give this error
```
root@kali:~# gem install fileutils
Fetching: fileutils-0.7.2.gem (100%)
ERROR:  Error installing fileutils:
	fileutils requires Ruby version >= 2.5.0dev.

```
my ruby -v is 

> ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

and here is the error report 

Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bcrypt_pbkdf-1.0.0 because its extensions are not built.  Try: gem pristine bcrypt_pbkdf --version 1.0.0
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring msgpack-1.1.0 because its extensions are not built.  Try: gem pristine msgpack --version 1.1.0
Ignoring network_interface-0.0.1 because its extensions are not built.  Try: gem pristine network_interface --version 0.0.1
Ignoring nokogiri-1.8.0 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.0
Ignoring pcaprub-0.12.4 because its extensions are not built.  Try: gem pristine pcaprub --version 0.12.4
Ignoring pg-0.20.0 because its extensions are not built.  Try: gem pristine pg --version 0.20.0
Ignoring pg_array_parser-0.0.9 because its extensions are not built.  Try: gem pristine pg_array_parser --version 0.0.9
Ignoring rbnacl-libsodium-1.0.13 because its extensions are not built.  Try: gem pristine rbnacl-libsodium --version 1.0.13
Ignoring redcarpet-3.4.0 because its extensions are not built.  Try: gem pristine redcarpet --version 3.4.0
Ignoring sqlite3-1.3.13 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.13
[*] Metasploit requires the Bundler gem to be installed
    $ gem install bundler

**Comment by peterpt** [comment]
gem install file-utils
and not
gem install fileutils

**Comment by sasatefa2009** [comment]
@peterpt  please look at this https://github.com/ruby/fileutils/issues/8

in the past few days a have updated and fixed alot of things in the ruby and the gems i have and i can totally say the problem is no on my side. 
the script you are using is a PoC and it's deprecated and abandoned by its developer.
IF YOU COULD JUST GET DOWN A LITTLE BIT, you will see that the developer has made an updated new version of it.

if you are lazy here it is https://github.com/xc0d3rz/metasploit-apk-embed-payload
