### ISSUE TITLE
install Aapt , dex2jar and apk tools not ok (Help Me pliz)

### ISSUE THREAD

**Issue by lachin58** [Screetsec/TheFatRat#180]
when i install Thefatrat Aapt.apktools and Dex2jar not install.
i read issue 123 and run cammand and screenshot
help me pliz

**Comment by peterpt** [comment]
1st : apt-get remove --purge aapt apktool dex2jar -y && apt-get autoremove -y
2nd :  rm -f /usr/local/sbin/aapt && rm -f /usr/local/sbin/apktool && rm -f /usr/local/sbin/d2j-* && rm -rf /usr/local/share/dex2jar 

This happens because you problably installed a previous version of fatrat before in a different directory , and then you deleted that directory but the symlinks created by that instalation were still in /usr/local/sbin folder .
So , now when setup checks if any of these tools are installed then it detects the symlink , but when it tries to run the symlink it gets an error and marks that tool as not installed .

**Comment by lachin58** [comment]
![2](https://user-images.githubusercontent.com/29653518/30240198-22e828e0-9581-11e7-8b7c-46f1a826b340.png)
 i worked your 3 guide but cant succeed.
![1](https://user-images.githubusercontent.com/29653518/30240194-1da5291e-9581-11e7-9ccd-85907e6c0ccd.png)

**Comment by peterpt** [comment]
execute setup.sh

**Comment by lachin58** [comment]
1st screen after excute setup.sh

**Comment by peterpt** [comment]
get me the output from this command : 
$PATH

**Comment by lachin58** [comment]
![1](https://user-images.githubusercontent.com/29653518/30245959-1bcd09d4-9600-11e7-85e2-bda034f2140e.png)

**Comment by peterpt** [comment]
in upper case 

not $path

like this : $PATH

and also , write : printenv

**Comment by lachin58** [comment]
![1](https://user-images.githubusercontent.com/29653518/30248549-05ab179c-963f-11e7-85a1-ea40bec08dbd.png)

**Comment by peterpt** [comment]
dont write "write: printenv"
WRITE only "printenv"

**Comment by lachin58** [comment]
![1](https://user-images.githubusercontent.com/29653518/30252181-c3e83d96-9682-11e7-89ad-d50bf6d24e93.png)
![2](https://user-images.githubusercontent.com/29653518/30252182-c49249d0-9682-11e7-9d01-e10f1c6f2867.png)

**Comment by peterpt** [comment]
ok , good .
It seems that if you write some command on terminal that is on /usr/local/sbin folder , then it will run .

Just do this on your terminal  :

rm -rf ~/TheFatRat && git clone https://github.com/Screetsec/TheFatRat.git ~/TheFatRat && cd ~/TheFatRat && chmod +x fatrat && chmod +x setup.sh && ./setup.sh

Since i have no idea which clone you have from fatrat , i need you to remove your existent directory of fatrat and clone the git again .

**Comment by lachin58** [comment]
thanks for all answers. i installed with above your answer but found new problem in below
![1](https://user-images.githubusercontent.com/29653518/30270053-6f4862b0-9700-11e7-9f0a-99543f48dbe5.png)

**Comment by peterpt** [comment]
apt-get remove --purge mingw-w64 -y && apt-get autoremove -y && apt-get install -f -y

then after this
execute setup.sh again from fatrat

**Comment by lachin58** [comment]
My internet not stable. I need cammand same
 --fix-missing for continue downloaded.

**Comment by lachin58** [comment]
![2](https://user-images.githubusercontent.com/29653518/30322285-2ffb65fc-97ce-11e7-81e3-6342e3df282f.png)

**Comment by lachin58** [comment]
i cant install mingw in fatrat pliz help
not any way for install?

**Comment by peterpt** [comment]
hey , i dont have all week to solve your issue , and this is not microsoft .
1st of all , get a stable internet connection , and then say something .

**Comment by lachin58** [comment]
i,m sorry MR  but i tried for this Rat 1 month . 
i think this problem last. not nervous for my . and for all helped unlimited thanks.
help pliz

**Comment by peterpt** [comment]
apt-get install -f && apt-get remove --purge mingw-w64 -y && apt-get autoremove -y 

then run setup.sh from fatrat with a stable internet connection , use google to translate from your language to english .

**Comment by lachin58** [comment]
I can installed fatrat. ThnQ for all helped
