### ISSUE TITLE
the-backdoor-factory & TheFatRat

### ISSUE THREAD

**Issue by Ghostboy-287** [Screetsec/TheFatRat#186]
Hello

the fact that **[the-backdoor-factory is no longer maintained or supported](https://github.com/secretsquirrel/the-backdoor-factory#the-backdoor-factory-is-no-longer-maintained-or-supported)** will not cause a **loss of efficiency of TheFatRat**?

**Comment by peterpt** [comment]
Backdoor factory finds holes in exe files and insert the payload there , so when user executes that exe the payload will run silently .
On notepad.exe from windows xp is possible to use backdoor factory to insert a payload , however on notepad.exe from windows 7 backdoor factory is unable to find the holes due to the sctructure code of those executables .
Since most of people these days use windows 7 and up , then fatrat is limited in providing options for new windows versions .
As long as new free tools are released on github to create modify exes in order to insert payloads , we will adapt fatrat to those tools , and if the old tools that fatrat uses now don't be maintained anymore then we will remove their code from fatrat .
