### ISSUE TITLE
Internet Local Only

### ISSUE THREAD

**Issue by Matechess** [Screetsec/TheFatRat#200]
Checking type of shell ....
[local]
 [ * ] Checking for internet connection
 [ X ]::[Internet Connection]: LOCAL ONLY!
 [X] Your Internet is not working correctly!
 [*] Checking ....
 You are connected to your local network but not to the web .
 Check if your router/modem gateway is connected to the web .

 Setup will not continue , you are only connected to your local lan.

 Setup will stop because :
 Ping google.com = Failed
 Ping google DNS = Failed

 Press [ENTER] key to continue

I use whonix-gateway in my Kali Linux 2.0. I don't know if that's the problem.

**Comment by peterpt** [comment]
Missing internet it means that over the terminal your linux is not able to resolve a domain address or your network interfaces are not configured correctly .
If you both open a terminal and write "ping google.com" you will get an error .
Fatrat tries to ping google dns with direct ip connection or by hostname , if both fail then it will popup that message you both received .
That issue is not related to fatrat code but to your linux network configuration .
