### ISSUE TITLE
Was not possible to install the packages labeled (Not Ok)

### ISSUE THREAD

**Issue by ComradeLoading** [Screetsec/TheFatRat#218]
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

What is this error? and how do I fix it? I am using Parrot Security OS. I have tried dozens of tutorials, and looked up the error code more times than I can count. And have found nothing, this is my last hope to figure out what this is and how to correct it. Thank you for your time.

**Comment by rohithgoud10** [comment]
same problem here

**Comment by peterpt** [comment]
it doesnt need to go to mars to undestand the message .
"Was not possible to install The Packages Labeled (Not Ok) "
setup of fatrat will popup which packages gave an error on installation .
The package with a label "Not ok" should be removed & purged before setup runs again .

This means that if for example , mingw32 is labeled as "not ok" , then user must uninstall it and purge it , so setup can install it properly .

These errors happen because most users are an adventurers in their linux , and start installing everything they see on the net , so , until this point there is nothing to point out , the problem is that users install scripts that require some package , and if that package is not properly installed then the new script ahead (ex: fatrat) do check if the package  exists , and then detect that package was not properly installed .

Labeled not ok means that user must insert this command on terminal .

apt-get remove --purge <package name> && apt-get autoremove

example for mingw32:
apt-get remove --purge mingw32 && apt-get autoremove

The setup was already written for noobs , but is not fail proof depending how is the mess in user linux distribution .

Sometimes the best way is just to avoid package installations automatically and let users to deal themselves with their missing packages , this way users would surely learn more about linux , instead coming here asking "how should i do" .

Before releasing a new version of fatrat , we test everything in a clean linux environment just to make sure everything works fine , so , on a clean linux without user experiments everything works without any issue .
Now , we can not write here every time someone posts an issue about something that was already solved before in a previous issue and it was closed .

My advice to you both is : 
- Check witch package was labeled "not ok" in setup
- search in closed issues of fatrat for that package

you will find the solution there .

**Comment by XluzSec** [comment]
![fat1](https://user-images.githubusercontent.com/24273330/39319080-9b14e3a0-499d-11e8-9e14-5efce433906a.png)
![fat2](https://user-images.githubusercontent.com/24273330/39319081-9baf55e8-499d-11e8-8bba-62194d38741f.png)


i cant to install setup.sh plz help me

**Comment by XluzSec** [comment]
im using ParotSec 
i have one error when i installing setup.sh
![fat11](https://user-images.githubusercontent.com/24273330/39319726-8cc4118e-499f-11e8-90f7-8f14de5b91dd.png)
![fat22](https://user-images.githubusercontent.com/24273330/39319728-8d0b0c24-499f-11e8-8860-e49561d55a7d.png)

anyone give me a solution?

**Comment by peterpt** [comment]
apt-get remove --purge mingw32 && apt-get autoremove && apt-get install -f
then read in this file : 
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

how to install mingw32 in your linux OS

**Comment by RohitYadav900** [comment]
apt-get remove --purge mingw32 && apt-get autoremove
