### ISSUE TITLE
Give option to FUD custom files

### ISSUE THREAD

**Issue by usmarine2141** [Screetsec/TheFatRat#219]
Please give option to make FUD custom files. :) @peterpt

**Comment by peterpt** [comment]
The tool to do that job in fatrat is backdoor-factory witch picks your custom exe and embed a backdoor in it , however this only works for old 32bit exes (not all) .
Backdoor factory development have been discontinued , so , don't have much faith from now on on your request because after all we just joined a bunch of tools in 1 single script (fatrat) and we wrote the script in a way that every person without any knowledge could create a backdoor .
EOD BKF : http://secureallthethings.blogspot.com/2017/08/closing-door-end-of-backdoor-factory.html
