### ISSUE TITLE
apk not installed

### ISSUE THREAD

**Issue by shaunrd0** [Screetsec/TheFatRat#22]
I was working on installing a backdoor on my android device, in case it is lost or stolen. The first .apk FatRat built installed perfectly, but every one after that has returned with an error "App not installed" I have set my device to allow 3rd party apps, and as I said the first .apk I tried installed just fine, I had messed up on my end and entered the ip incorrectly. I even, in a desperate attempt, tried building a new .apk with the same errors as my first one, and IT would not install on the device.
https://www.youtube.com/watch?v=yoMIbG1JJ74
That is the tutorial I have followed exactly, it's a pretty simple process and I've damn near memorized it at this point. 
-Do I need to remove my first installation to try a different one?
-Where does the .apk install to on the device?
-Am I able to change the lhost and lport on the .apk after it has been created, instead of creating multiple .apk files?
-Is there a different process that I am unaware of since I am on a virtual machine (Kali) running on windows 10?

You don't need to walk me through it if there is a nice tutorial or bit of information somewhere that I haven't found just link me and I'll be on my way. Appreciate any help in advance. Sorry to bother, hope I'm in the right place.

**Comment by deltaxflux** [comment]
So here are some answers 
1. Nope, There is no differences between the first on second version. The file will get generated every time the same
2. Normally you find all files here: /data/data/"[name]"
3. Nope, because the file need to recompile every time
4. Some ideas: Dual boot with linux / Live boot with linux 

And in general this app is always a 3 party app. You need to deinstall and reinstall the app to prevent errors. Hope that help you

**Comment by shaunrd0** [comment]
This was exactly what I needed. Thanks, deltaxflux. Appreciate the info! After finding the previous install and removing it, I was able to complete the process with no trouble.
