### ISSUE TITLE
Cant install fatrat

### ISSUE THREAD

**Issue by ryneharris** [Screetsec/TheFatRat#227]
Unable to read file triggers file 'var/lib...... i can send  a photo of the problem  plz help me

**Comment by peterpt** [comment]
happily i am not clairvoyant , because if i was then life at its whole had no fun to me knowing what was going to happen right ahead .
So , if you think that your error is a common error that every fatrat installation have , then you are wrong .
And by this i mean : without more information about the issue i am unable to help you .
