### ISSUE TITLE
i cant run fatrat 

### ISSUE THREAD

**Issue by XplsXjokes** [Screetsec/TheFatRat#236]
can you help me?
![screenshot at 2018-02-02 12-50-26](https://user-images.githubusercontent.com/36073755/35732321-444eacf6-0819-11e8-9eef-23a5c546a8b7.png)

**Comment by XplsXjokes** [comment]
i cant install mingw-32 and i think that its not posseble

**Comment by XplsXjokes** [comment]
i tyed this too ![screenshot at 2018-02-02 13-12-05](https://user-images.githubusercontent.com/36073755/35732682-b6129c98-081a-11e8-8e9e-9e9f863d6846.png)

**Comment by peterpt** [comment]
apt-get remove --purge mingw32 && apt-get autoremove && apt-get install -f 

then run setup again .

I an tired to write always the same thing because it is more easy for user to create a ticket than search on closed issues .

**Comment by XplsXjokes** [comment]
![screenshot at 2018-02-04 15-39-11](https://user-images.githubusercontent.com/36073755/35778644-8d21f308-09c1-11e8-9b8d-1d09148215b5.png)

**Comment by XplsXjokes** [comment]
i looked everything i tryed dont be an asshole

**Comment by XplsXjokes** [comment]
it was the source.list i had to edit no one mentoined that

**Comment by peterpt** [comment]
Fatrat uses kali sources.list , fatrat only uses your sources list for a few tools .
Mingw32 is installed from kali repository and not from your sources list .
So , if you think that using "apt-get install mingw32" will be installed from your linux sources.list repositories then forget it , because this tool have probably another name in parrot repository .

No one have to mention anything to you , if your sources list are empty then you are unable to recieve updates to your linux no matter how many times you write "apt-get update" .
