### ISSUE TITLE
./backdoor_apk: Failed to add hook

### ISSUE THREAD

**Issue by shuhrat02** [Screetsec/TheFatRat#238]
hi everyone, tried to bind instagram.apk. During the bindig, stopped with error '[!] Failed to add hook
'

 
```
[*] Creating RAT Apk File...done.
 
[*] Decompiling RAT APK file...done.
 
[*] Decompiling original APK file...done.
 
[*] Merging permissions of original and payload projects...done.
 
[*] Running proguard on RAT APK file...done.
 
[*] Decompiling obfuscated RAT APK file...done.
 
[*] Creating new directories in original project for RAT smali files...done.
 
[*] Copying RAT smali files to new directories in original project...done.
 
[*] Fixing RAT smali files...done.
 
[*] Obfuscating const-string values in RAT smali files...done.
 
[*] Locating smali file to hook in original project...done.
 
[*] Adding hook in original smali file... 
./backdoor_apk: строка 107: [: too many arguments
done.
 [!] Failed to add hook

Press [ENTER] key to continue to return to fatrat menu

```

pls, help! tnx in advise

**Comment by peterpt** [comment]
There is no help that can be supplied to this error .
Read readme.md check from where backdoor-apk was picked and consult its developer .
We did not build backdoor-apk or any of the other tools in fatrat , we just build the interface to use those tools more easier . If a tool do not output what you was expecting then it is because that tool was not written by original developer to handle with that output you request .
We are unable to do anything about that .
We already replied to dozens of posts like yours , and we always told the same thing .
