### ISSUE TITLE
Monodevelop not installing

### ISSUE THREAD

**Issue by blackopps** [Screetsec/TheFatRat#243]
Hi,

i have a problem installing monodevelop if i ran setup.sh it says installing monodevelop but it`s not installing it.
how can i fix it?
![virtualbox_kali linux_05_02_2018_18_32_40](https://user-images.githubusercontent.com/36159848/36274230-13a9db7c-12ad-11e8-9716-9262b666b6f5.png)

**Comment by unixproject** [comment]
brother you need first update and upgrade your distro and then install all the shit
add the sources list from 
https://docs.kali.org/general-use/kali-linux-sources-list-repositories
 apt-get clean && apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y

**Comment by peterpt** [comment]
For what i can see in your print screen , apt is locked , problably because you have opened synaptic package manager , or another terminal running apt-get install some package .
If that is not the case and if for some reason the lock file was not properly deleted by the recent apt command or synaptic then write this in your terminal .

rm -f /var/lib/dpkg/lock

doing this then when you write again apt-get , the apt tool will not find the lock file and it will run without issues .
