### ISSUE TITLE
mingw-32 did't install kali 2018.1

### ISSUE THREAD

**Issue by myda101** [Screetsec/TheFatRat#246]
xterm -> OK
Dns-Utils -> OK
GCC -> OK
Apache2 -> OK
Gnome Terminal -> OK
UPX -> OK
Ruby -> OK
Openssl -> OK
Jarsigner -> OK
Unzip -> OK
Keytool -> OK
Mingw64 -> OK
mingw-32 -> Not OK
DX -> OK
Aapt -> OK
Apktool -> OK
Dex2Jar -> OK
Metasploit -> OK
Backdoor-Factory -> OK
Searchsploit -> OK
Was not possible to install The Packages Labeled (Not Ok) in this list above
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)
before running fatrat setup script again

**Comment by ragavravi** [comment]
Check this Closed Issue...
I went through the Same...
I hope it will be helpful... :-)

https://github.com/Screetsec/TheFatRat/issues/244

**Comment by SheesAli** [comment]
Try this
https://www.youtube.com/watch?v=CXvTKtYdm3Q

**Comment by peterpt** [comment]
SheesAli i will remove your video because it is not a solution .
You are disabling the mingw instalations from the code , and what will give in fatrat is that user will be unable to execute most of backdoors compilers for windows .
Without mingw only apks will work .

**Comment by myda101** [comment]
the only way to **solve** this problem is by:  `apt update && apt upgrade` before installing FATRAT `` 
 
to upgrade kali to the latest version vist kali docemnts web site for more info

**Comment by peterpt** [comment]
Actually there is no problem at all if the linux that user is using it is in order without broken packages .
People that come here complaining about mingw issues don't have a clue about linux , so they pick everything on the web and try to install the dependencies , but if the dependencies are not installed successfully then they will not fix the problem , they just leave it that way .
Then when an automated installation script like setup of fatrat starts , it founds difficulties installing the dependencies to work because the precious ones were not solved successfully by the user .
I don't have any issue installing fatrat from scratch , and every time we release a new version , we test it first .

**Comment by myda101** [comment]
I know that first time when that happened to me I wasn’t updated my kali because I forgot to do so I got this issue. But if the linux is installed properly & always updating..  No body will face any issues with FATRAT or any thing else. Thank you peterpt for you’re time replaying to all of the issues.
