### ISSUE TITLE
[Feature Request] Detection Reporting

### ISSUE THREAD

**Issue by zero77** [Screetsec/TheFatRat#28]
Can you build in the option for people to anonymously report if a payload has been detected by a specific AV, which would then appear next to the payload and also show which AV it was detected by.
Thanks

**Comment by peterpt** [comment]
Most AV online file scanners send the infected files to antivirus companies to be analyzed .
However , http://nodistribute.com does not do that for now , but we are not thinking in adding that option because everyone will use it and at same time the rat files start to be detected by AV more often .
Maybe in future who knows ;) .

After the creation of your rat file , upload it to the site i wrote before to check for AV detections , if you want to test it .
