### ISSUE TITLE
APK Error and Network Error

### ISSUE THREAD

**Issue by Stephen1023** [Screetsec/TheFatRat#298]
My first problem is when using number 5, "Backdooring Original APK." 

[apk.log](https://github.com/Screetsec/TheFatRat/files/2224113/apk.log)

I am using "android/meterpreter/reverse_tcp" and "Use Backdoor-apk 0.2.2"

-------------------------------------

My second problem is when I use any that work (specifically "create backdoor with msfvenom") and use the "signed android apk."

Everything goes smoothly until in msfconsole and run the command, "exploit," where I get a network error. For my Lhost I use the external network it provides. Which matches with "whatismyip." I also port forwarded the port I am using and I also tried with other ports to make sure it wasn't just that port.

After it fails to connect to my network it tries 0.0.0.0:Port and still fails. Could this be because I am using a virtual machine and I port forwarded the IP to my computer? They both have the same external ip but do they have different internal ip's? Thanks.

**Comment by peterpt** [comment]
On a virtual machine you dont need to forward ports on router or anything else .
Configure your VM to use bridged network interface instead using NAT .
If you use bridged interface then the VM will get an ip on same subnet , and then it will be possible to connect to your metasploit .
If you use nat interface then the VM will get a different ip range from a different subnet and will not connect to msf .

The issue you created is not a bug in the script of fatrat , but a lack of knowledge from yourself to make things work .
Sadly , these types of issues flood the github where people think that just because we gave them the dish with the meat inside , they also think that we have the obligation to serve themselves on their mouth .
