### ISSUE TITLE
There was an error creating your FUD rat with Powerstager

### ISSUE THREAD

**Issue by hanskdw** [Screetsec/TheFatRat#311]
how do i fixx thiss?

There was an error creating your FUD rat with Powerstager

**Comment by peterpt** [comment]
without the log is impossible , but i advise you to read this link : 
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md

If you were not follow others advices here to bypass the missing fatrat packages to run the tool , then the troubleshoot text will solve your issue .
Otherwise , if you somehow changed the code of setup in fatrat then troubleshoot will not solve this issue neither do us .
