### ISSUE TITLE
Need solution for arm8l device

### ISSUE THREAD

**Issue by Anik0077** [Screetsec/TheFatRat#312]
Setup will not proceed because none of these archs were detected
x86_64|i386|i486|i586|i686|aarch64

Your linux arch: armv8l is not supported

Press any key to continue

**Comment by peterpt** [comment]
We do not active those architectures because : 
- Not everyone uses the same linux distribution 
- Lot of complications in trying to get things working
- Some packages are missing for arm
- Fatrat is heavy , specially when it calls metasploit-framework

By this , Running an android , with a linux VM inside & metasploit-framework it will be an headache for us to keep the patience when you all pop up with issues , asking us to solve them because some how you all think this is microsoft .

Until now 80% of the issues in this git are related to package installations and not fatrat directly issues in the code .
