### ISSUE TITLE
No APK file found in /output/ folder

### ISSUE THREAD

**Issue by Marcono23** [Screetsec/TheFatRat#326]
1) I created a backdoor with mfsvenom
2) Chose no.3 signed Android to fatrat.apk
3) Enter my local host IP and port
4) Entered base name for output file
5) Chose no.3 android/meterpreter/reverse_tcp
6) Rat payload created
7) Valid certificate created
8) Payload apk signing done
9) Created listener and name it
10) Message says "configuration file saved to /TheFatRat/config/listeners/name.rc
11) "Payload apk was created and signed and located in /TheFatRat/backdoored/name.apk

Now these are the steps i took and the problem is there are NO such file in these folder. Please help. TQ

**Comment by Jeeonesign** [comment]
Check the output folder!..

**Comment by peterpt** [comment]
we did some upgrades in fatrat , make sure you clone again fatrat , and then tell us if that problem persists  .
However let me remind you that the issue you are referring are out of our hands , the reason is that fatrat is a tool that uses a lot of other tools , and the error you are reporting belong to the "other tools" , witch is out of our range of capabilities to solve it for multiple reasons .

**Comment by furkan9ne** [comment]
Friends, I do not have the output folder, the rats I created are not visible, please help me
