### ISSUE TITLE
Mono-Denvelop Utils -> Not OK

### ISSUE THREAD

**Issue by wizard54** [Screetsec/TheFatRat#334]
Hello,
I reinstalled my KaliLinux on my new laptop, so my system is a clean install.
I would like to install TheFatRat but when i run ./setup.sh it raise me an error message about : "Mono-Denvelop Utils -> Not OK". It list me commands to run but nothing fixed.

Anybody can help me to solve it please 
best regards 

<img width="1440" alt="capture d ecran 2018-12-17 a 14 11 42" src="https://user-images.githubusercontent.com/29359840/50089337-e0231b80-0205-11e9-961b-77d6afea4a57.png">

**Comment by peterpt** [comment]
echo "deb http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list
apt-get update 

and then run setup.sh

**Comment by peterpt** [comment]
After installing fatrat successfully then run this command on your terminal :
 
sed -i '/stretch/d' /etc/apt/sources.list
apt-get update

**Comment by allyjailawi95** [comment]
Hallo i have the same problem and i followed the instruction till i encounter this error
After i update "apt-get update" i encounter this error
 
Reading package lists... Done
W: GPG error: http://download.mono-project.com/repo/debian wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF
W: The repository 'http://download.mono-project.com/repo/debian wheezy InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://security.kali.org/kali-security kali/updates Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://http.kali.org/kali kali Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://download.mono-project.com/repo/debian vs-stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A6A19B38D3D831EF
W: The repository 'https://download.mono-project.com/repo/debian vs-stretch InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://security.kali.org/kali-security/dists/kali/updates/contrib/source/Sources  404  Not Found
E: Failed to fetch http://http.kali.org/kali/dists/kali/contrib/source/Sources  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@kali:~# apt-get update

**Comment by peterpt** [comment]
That is not a fatrat issue , that is a problem in a missing key in your apt repositories
