### ISSUE TITLE
./fatrat: line 2116: $log: ambiguous redirect

### ISSUE THREAD

**Issue by GasbaouiMohammedAlAmin** [Screetsec/TheFatRat#337]
*] Creating RAT payload with msfvenom
./fatrat: line 2116: $log: ambiguous redirect

 
There was a problem in the creation of your rat apk file , make sure your metasploit is running correctly
 
Press [ENTER] key to return to fatrat menu
![screenshot from 2019-01-28 00-17-35](https://user-images.githubusercontent.com/38020387/51808284-40d85600-2292-11e9-9c4a-10afbee7baa2.png)
i did not found apk.log

**Comment by peterpt** [comment]
echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list
echo "deb-src http://http.kali.org/kali kali-rolling main non-free contrib"  >> /etc/apt/sources.list
apt-get update -y && apt-get upgrade -y && apt-get dist-upgrade -y

**Comment by peterpt** [comment]
that ambiguous reedirect happens because 90% of the script was wrote in some kind of rush (fast code) , if you open the script with a text editor you will see many variables not closed to avoid that error .

by this i mean this

blablabla $somevariable 

the correct code for this would be : 
blablabla "$somevariable"

or
blablabla '$somevariable'

i will close this issue because this is a problem that we are unable to solve it in 1 stroke , we have hundreds of lines of codes to verify and update to update we fix a bunch of them .
Eventually in version 1.9.8 or 1.9.9 this issue will be solved .

**Comment by smileofverse** [comment]
ping for ngrok link to get ip add 

put ip in fatrat dont add ngrok link
