### ISSUE TITLE
Signing executable to bypass smart screen's "Don't Run, more info" prompt.

### ISSUE THREAD

**Issue by dsx12** [Screetsec/TheFatRat#339]
Every executable generated nearly cannot be run without signing the executable file.

Is there a way around this? is it possible to bypass smart screen and if there's a way please share the knowledge!

**Comment by peterpt** [comment]
I added your topic as an enhancement to the tool , and to be honest and after thinking for a while on the subject i personally decided that i will not implement that option in fatrat .
Here is is the reason : 

Fatrat is for pentest , and 80% of the users here are using it to infect innocent people on the web by placing the executables on websites disguised as apps for windows  , what happens is that when the "no experience visitor" executes the executable then will reverse a shell to the attacker .
Until this part i did not care much because it was some kind of lesson to dont download pirated software .
However , here comes the reason why i really will not implement it , not everyone that uses this tool is a noob on the web , and some of them dont even create issues when they found a problem in the code of fatrat , they just fix it for themselves , these types of users are advaced user that can easily create a crypter to encrypt the victim computer and then ask for money ahead in bitcoin so he/she don't be traced back .
Now if i implemented what you were asking then the victim after executing the rat executable will see that was a signed executable by Microsoft and will press the run button ahead thinking that was not a virus , but if do not implement the code then i will give a chance to those people to what that the publisher of that executable is "unknow" , and by this is not to be thrust , and by this the victim will try his/her own chance by executing or not the rat that at that time have no clew what it is .

So , forget it .
