### ISSUE TITLE
Antergos (Arch) post-install and startup error messages

### ISSUE THREAD

**Issue by Davetheraveuk** [Screetsec/TheFatRat#342]
Hi, 
So I installed TFR via the blackarch repo (I am using antergos and manually added blackarch repo).
I fired up TFR and received the following error messages:

```
____ _               _    _                   
  / ___| |__   ___  ___| | _(_)_ __   __ _             
 | |   | '_ \ / _ \/ __| |/ / | '_ \ / _\ |            
 | |___| | | |  __/ (__|   <| | | | | (_| |  _   _   _ 
  \____|_| |_|\___|\___|_|\_\_|_| |_|\__/ | (_) (_) (_)
                                     	|___/    
-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | Hacker Indonesia 
-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- 
 
 [!]::[Check Dependencies]:
 [✔]::[Distro]: Antergos
 [✔]::[Release]: n/a
 [✔]::[Check User]: root
 [✔]::[Terminal]: local
 [ X ]::[Internet Connection]: OFFLINE!
 [X] Your Internet is not working correctly!
 [*] Checking ....
 [X] Your linux OS is not able to resolve hostnames over terminal using ping !!

 Search on the web : (unable to resolve hostnames ping) to find a solution

 Fatrat will continue , but some of its functions may not work properly.

 Press [ENTER] key to continue

```
Okay this is weird because my internet connection is _online_ and working fine.
I did as TFR suggested and search the web for "unable to resolve hostnames ping" but nothing came up for TFR using an Arch based distro.

Any ideas?
Let me know if you require any more information.
Thanks.
Dave.

**Comment by peterpt** [comment]
It is indeed strange that happening to you , because the setup uses the same routine of checking for internet connection .
1st - fatrat tries to connect to google.com on port 80 using netcat 

in case fails then

tries the ping google dns google.com

if fails then ping google dns ips 

what happened is that somehow if you write in your terminal "ping google.com" you will have an error , it could be related to your hosts or dns configuration on your router ahead .

Fatrat continues to its menu and do all the stuff , but you should check why your machine is not resolving dns names thru the dns server configured in your router or in linux resolv.conf .

**Comment by Davetheraveuk** [comment]
Okay so i have spent a good few hours trying to resolve this problem.
I have had no joy and I am out of patience.

Is there an alternative to TFR ???

**Comment by peterpt** [comment]
fatrat will work as it is , if i am not mistaken , you are able to get to its menu , the problem ahead could be related by creating stuff in fatrat with domain names on it witch i am not sure if your system will sove them to allow the connection from the domain to a specific ip .
As long as you use ip addresses then you will not have any issue , i think .
Nope , from my knowledge i dont know any alternative to it FTR (FATRAT) in my mind right now .

Fatrat allows you to enter the menu because it was able to ping google dns ips , if that has failed too then you will not able to enter in its menu .

**Comment by peterpt** [comment]
forgot to mention , maybe if you setup a static lan ip address on /etc/network/interfaces  with dns name servers like opendns could fix your problem .
But since i never had that issue then i am not sure how to solve it . 

https://www.tecmint.com/set-add-static-ip-address-in-linux/

open dns ip servers are : 208.67.222.222 · 208.67.220.220

this is an example .

**Comment by peterpt** [comment]
just update to new version and everything will be fine .
We changed the way how fatrat detects your internet connection .
