### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager

### ISSUE THREAD

**Issue by verapex** [Screetsec/TheFatRat#353]
when i try create FUD rat whit Powerstager, i have an error... 
i used 4.19.0-kali4-amd64
when i try ~/TheFatRat/tools# python3 power.py its working 
and i read #352 i used .(/powerstager.py --meterpreter) its didnt work.. didnt connect payload client  
[fudwin.log](https://github.com/Screetsec/TheFatRat/files/3177377/fudwin.log)
[setup.log](https://github.com/Screetsec/TheFatRat/files/3177379/setup.log)

**Comment by peterpt** [comment]
write "python -V" in your terminal and then write here the output you get from it .

**Comment by verapex** [comment]
i think u right.. default python Python 2.7.16... maybe i must change it python3

**Comment by peterpt** [comment]
nop , the powerstager.py inside fatrat runs win python 2.7 and not 3.x , did you changed or replaced any script inside tools folder in fatrat ?

**Comment by peterpt** [comment]
Forget it .
It was something you wrote in preparing the payload , powerstager does not work with domain names as lhost , just ips .
in here : No such file or directory: 'google'
you wrote something with google name when you were preparing the payload in fatrat fudwin with power stager

**Comment by peterpt** [comment]
Actually i want you to do something just to check out one thing .
Open a terminal console and write these commands :

cd /root/TheFatRat/tools/
python power.py

and then take a print screen and upload it here .

**Comment by verapex** [comment]
its work... python or python3.. but i dont understood what do u mean "you wrote something with google name when you were preparing the payload in fatrat fudwin with power stager"... google is output file name

**Comment by peterpt** [comment]
What happens is that somehow the script was unable to write the filename .
Print.info) IOError: [Errno 2] No such file or directory: 'google'
when script asks for filename it actually is only a filename and not a directory behind like
"google/google"
or
"/google/google"

That error looks to me that somehow you wrote a directory name behind the filename and then the script had an error because that directory does not exist , and this is why :

IOError: = Input/output Error , same thing as reading or writing a file
[Errno 2] =  Code Error
 No such file or directory: 'google' = No such file or directory it means that somehow there was presented a directory in the script that does not exist , and since the script is not prepared to write in case not found then stops there .

**Comment by verapex** [comment]
> Print.info) IOError: [Errno 2] No such file or directory: 'google'

yes.. and really dont understand... .if can try ./fatrat i didnt create payloads, but when i write ./power.py payloads its ok.. :)

**Comment by verapex** [comment]
loll... soryy pls close this topic.. my mistake... when the script ask me output name, i just wrote google, not google.exe.. i try and wrote google.exe and no error

**Comment by peterpt** [comment]
ok .

**Comment by ranaali12346161** [comment]
[x] There was an error creating your FUD rat with Powerstager .
i am getting this error. kindly help me out
my fatrat folder doesnot have output folder also.

**Comment by adada111** [comment]
but i don't know ，how to sloveit？

**Comment by adada111** [comment]
I don't know how to solve this problem

**Comment by hdawg12** [comment]
> ok .

My does the same thing. when I write test.exe, it creates the output file, but with an extra .exe. So it looks like test.exe.exe

**Comment by peterpt** [comment]
https://github.com/Screetsec/TheFatRat/blob/master/troubleshoot.md
