### ISSUE TITLE
TheFatRat Monodevelop Not OK 

### ISSUE THREAD

**Issue by PKacper** [Screetsec/TheFatRat#368]
I know that there was hundreds of issues with that but i checked all of them and non of them looked like my one i need help as soon is possible if anyone could help me solve the problem i could pay some money.
![Screenshot from 2019-08-07 20-46-38](https://user-images.githubusercontent.com/53877833/62653198-f593b400-b954-11e9-9972-1ec2407bcfb2.png)

**Comment by peterpt** [comment]
post here apt.log in your log files , in case you dont have it then update your fatrat and do everything all over again .
In case you insist without that log then your issue will be closed and locked .

**Comment by PKacper** [comment]
Dear peterpt

where is that apt log located?
if you could explain me Step by Step it would be great.
Im from UK my main goal is to hack an android phone if you could show me
how to do it i will pay you The amount you want.
Kindest regards Kacper

**Comment by peterpt** [comment]
On the latest release of fatrat it will be created a log file inside the "logs" folder in fatrat directory called "apt.log" , if that file is not there then it is because you are using an old version of fatrat .
That specific log collects information about witch packages your repository list have that fatrat may need and witch ones does not .
So to identify your specific issue , i have to see that log .

**Comment by PKacper** [comment]
![Screenshot from 2019-08-09 06-57-18](https://user-images.githubusercontent.com/53877833/62757461-4f8a9b80-ba73-11e9-8b8b-bbb50f47a648.png)

**Comment by PKacper** [comment]
https://user-images.githubusercontent.com/53877833/62757461-4f8a9b80-ba73-11e9-8b8b-bbb50f47a648.png

**Comment by PKacper** [comment]
This is it
https://user-images.githubusercontent.com/53877833/62757461-4f8a9b80-ba73-11e9-8b8b-bbb50f47a648.png

**Comment by peterpt** [comment]
Please post the full log file , i need to know witch repositories are your OS using .
And this next time before sending it , write this in your terminal :

apt-get clean && apt-get clean cache

then run again the setup.sh from fatrat and drop here the log file .

I am asking this because according to the log , the mono-mcs exist in your repository , witch is the problem you have right now , but that could also be a false positive due to probable previous repositories you may have in sources.list , this is why i need you to clean your apt cache and do it all over again just to make sure .

**Comment by PKacper** [comment]
Dear peterpt

I did what u requested me to do there is the apt.log after (cleaning)
I would also like to get in touch with you on my email and i hope that my
offer would be good for both of us.
kacperkubicz86@gmail.com
Im waiting for your response on my email and also about my problem with
TheFatRat

Regards Kacper

**Comment by peterpt** [comment]
Look , i dont do this for money .
I only want to know what is your linux distribution , witch repositories are you using so i can identify what is the problem , and if i identify that i should change the source code to improve it then i do it .
For your information , the information that apt.log collects are nothing confidential .

1st are the packages that fatrat uses , and i checks your current repositories for them .
2nd - gets your PATH environment (this one i implement it because people that have problems installing (apktool , dx , and some other tools that come inside fatrat) can not do it because they dont have in their path environment this link "/usr/local/sbin" , witch is where these tools are installed .

3rd - are your repository lists where your linux retrieves the updates , the repositories are no secret , they are public for everyone .
Here it is an example of an online link to generate the repositories for the debian releases :
https://debgen.simplylinux.ch/

These ones are for kali distribution :
https://docs.kali.org/general-use/kali-linux-sources-list-repositories

these are for devuan distributions
https://devuan.org/os/etc/apt/sources.list

So , there is no secrets to be show in that log .
Just drag the file from your file explorer to this issue like you did with the picture .
any problems watch this video .
https://www.youtube.com/watch?v=mGXFVxDlWgU

**Comment by PKacper** [comment]
[apt.log](https://github.com/Screetsec/TheFatRat/files/3493809/apt.log)

**Comment by PKacper** [comment]
![Screenshot from 2019-08-12 20-28-17](https://user-images.githubusercontent.com/53877833/62888690-bc35bc80-bd37-11e9-8d07-b1b68a748583.png)

**Comment by peterpt** [comment]
ok , the problem is that you dont have any repositories in your sources.list , the ones that you think you have are the ones that come with the dvd .

write this in your terminal :
echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list
echo "deb-src http://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list
apt-get update && apt-get upgrade -y 

then after your linux gets upgraded (it may take a while) , run setup.sh from fatrat and everything will be fine .

**Comment by PKacper** [comment]
/usr/lib/dradis/ruby/2.5.0/gems/railties-5.1.7/lib/rails/application/configuration.rb:139:in `database_configuration'
Could not find command "dradis:setup:migrate".
Setting up ruby-cms-scanner (0.5.7-0kali1) ...
Setting up libdjvulibre21:amd64 (3.5.27.1-12) ...
Setting up p7zip-full (16.02+dfsg-7) ...
Setting up wpscan (3.6.3-0kali1) ...
Processing triggers for man-db (2.8.6.1-1) ...
Processing triggers for postgresql-common (200+deb10u1) ...
supported-versions: WARNING! Unknown distribution: kali
debian found in ID_LIKE, treating as Debian
supported-versions: WARNING: Unknown Debian release: 2019.3
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
  en_us
Removing obsolete dictionary files:
Processing triggers for libc-bin (2.28-10) ...
thats what it said at the end and i could not take a screen shot

**Comment by peterpt** [comment]
Dont worry everything is fine ,The problem was that you did not update your linux for several months since the dvd release , your linux was updated until february only , because the kali release you have is the 2019.02 , so you did not upgraded your linux for 6 months  , that dradis error is no issue because after all i have serious doubts that you know what dradis does or if you ever use it , anyway , just write :

apt-get install -f -y && apt-get upgrade && apt-get dist-upgrade

**Comment by PKacper** [comment]
So Mr Peterpt  iv'e did what u told me to do and after all i have the same problem.
I upgraded everything changed the source but sill stuck in the same place.

**Comment by peterpt** [comment]
write in your terminal "apt-get install mono-mcs" and drop here the print screen of that operation .

**Comment by PKacper** [comment]
![Screenshot from 2019-08-18 15-40-26](https://user-images.githubusercontent.com/53877833/63225986-d3a8f580-c1ce-11e9-97ce-3883e58eec11.png)

**Comment by peterpt** [comment]
Screenshot out of context .
