### ISSUE TITLE
could you please stop `apt autoremove`?

### ISSUE THREAD

**Issue by kmahyyg** [Screetsec/TheFatRat#371]
some packages are intended to leave here for future usage, please STOP using `apt autoremove -y` inside your script.

**Comment by peterpt** [comment]
Nope , autoremove is needed to remove automatically broken packages in user system , if you want anything that will be removed just do apt-get install "what you need" after the autoremove , because after all sooner or later those packages will be removed when you upgrade your distribution to a new release .
