### ISSUE TITLE
Not able to download apache2?

### ISSUE THREAD

**Issue by eren123danyel** [Screetsec/TheFatRat#395]
I can't find apache2, i'm currently on mac and using fink to install apache2 if that helps, fink can be used to download modules, but it also allows for the command apt-get if that's of any help.

With apt-get i get the error:
```
Reading Package Lists... Done
Building Dependency Tree... Done
E: Couldn't find package apache2
```

with fink install i get the error:
```
curl: (22) The requested URL returned error: 404 Not Found
### execution of curl failed, exit code 22
```

Is there a better way to install it?

**Comment by eren123danyel** [comment]
Update: I'm pretty sure apache2 isn't available anymore? Maybe you should change it to use httpd? (Btw i have no idea what i'm talking about it, just trying to find a reason it might not work)

**Comment by peterpt** [comment]
the problem is that we did not build the tool for Macintosh OS systems .
Despite the fact that MAC OS is a closed fork from LINUX , we expect the users of this tool to use Linux OS Systems .
The reason is pretty simple , i dont have a Mac and i dont want to , and secondly i have no idea how mac os works .
