### ISSUE TITLE
Fatrat not working for Android 10 or 2020 apk 

### ISSUE THREAD

**Issue by AMASHALA** [screetsec/TheFatRat#425]
Am following all steps but on listening part nothing showing after installing the apk generated by fatrat.
In details 
1. Open fatrat 
2. Choose option 5
3. Provide apk path 
If it new apk not working and saying failed. 
If it old apk it sucess. 
4. I uploaded the generated apk by fatrat 
5. Download it on Android 10 device and install it 
6. I opened msf console, set lhost lport exploit, then service started listening but nothing show in terminal. 
Any ideas.

**Comment by Screetsec** [comment]
The android must running to for getting backconnect

**Comment by Screetsec** [comment]
Upload detail information - Following intrustcion tu sbmit here

https://github.com/Screetsec/TheFatRat/blob/master/ISSUES.md

**Comment by Morsmalleo** [comment]
I am having the same issue, i posted my own issue about this

I have successfully installed fatrat on Kali Linux 2020.1 

And have backdoored an original .apk file using the number 2 (Old FatRat method) simply because the 1st option of backdooring an apk is outdated, anyway everything gets done and i install the backdoored apk on my Samsung Galaxy S7 rooted with magisk and running android 9 on lineageOS, but nothing happens on metasploits end

**Comment by HK-dot** [comment]
same error i get any idea what to do ?

**Comment by peterpt** [comment]
If not on same network then dont expect miracles , its like saying the android that you are in NY while in reality you are in Texas .

**Comment by Haswanthkumar** [comment]
Hi peterpt 
Actually victims phone is also on the same network like victim phone is connected to the same wifi which I connected and I have checked sessions -l there is no luck

**Comment by peterpt** [comment]
try an apk payload only using option 1 in fatrat and select option 3 (signed apk android) .
Then install it and try it to see if it works .

**Comment by Morsmalleo** [comment]
backdoored apk's wont work with the "Backdoor Apk" option just above "the old fatrat method" (option 2), only on some older APK files it will work, due to the backdoor apk option being outdated (broken) as explained in another FatRat issue by @peterpt 

however when choosing the option 1 to create a standalone msfvenom payload, it works fine, and if using a virtual machine make sure you have bridged adapters enabled, otherwise the payload wont connect back to the meterpreter session after being installed and opened on the victim phone

**Comment by Morsmalleo** [comment]
if you are not using a virtual machine then you need to enable port forwarding in your router,
another way of doing this without port forwarding which seemed to work for me is by using ngrok and copying and pasting the ngrok server ip address and port number as the LHOST and LPORT on metasploit

**Comment by 4445MB** [comment]
If you are getting an erro hiding payload  into exiting app or payload don't connect to android version 10 working on.send an email to arivarasankg@gmail.com

**Comment by Kapil231** [comment]
My payload is create successfully with option 1,  but when I am installing it in victim's phone, I don't get any reverse connection.

**Comment by Kapil231** [comment]
while using msfvenom, it works fine for android version 7.0
But when i am installing it in android 10, it says" this app is build for older version of android, might not work properly. please contact developer"
Meterpreter sessions continues to open and close.
i am unable to execute any command.

**Comment by peterpt** [comment]
Payload is generated by metasploit , maybe metasploit has not yet made their framework to fully integrate with android 10 . Have no idea .

**Comment by 4445MB** [comment]
Meatsploilt don't generate payload, msfvenom dose ,it's works ....do you
use tcp?  .


Please donate to support us 1GsLw4XigzhbNqsw17RTHuRJcdPchwEbQp

**Comment by 4445MB** [comment]
Are you using tcp ? Do you hide the payload on a file or app ?


Please donate
1GsLw4XigzhbNqsw17RTHuRJcdPchwEbQp

**Comment by 4445MB** [comment]
It's works fine ,do you want to learn as a noob ?


Donate
1GsLw4XigzhbNqsw17RTHuRJcdPchwEbQp

**Comment by Kapil231** [comment]
yes, I am using tcp. 
when I hide the backdoor on any app, it doesn't work.
When i install the APK backdoored by FatRat on victim's phone, it doesn't ask for any permissions.

**Comment by 4445MB** [comment]
Its works perfectly ,some device has patch those linkage ,we will teacj you
but do you mind buying us coffee ?.

**Comment by 4445MB** [comment]
Por forword & vpn use this and  locate your target protocel ,also understand LAN WAN & TAN .

**Comment by MissMinFu** [comment]
> g a virtual machine then you need to enable p

hello friend,i wonder know hava you fix the problem.

**Comment by wizardfebin** [comment]
I generated payload to an apk using option 5 and when i tried to install  it shows "app not installed" on android 10 and android 6

**Comment by hiime** [comment]
> while using msfvenom, it works fine for android version 7.0
> But when i am installing it in android 10, it says" this app is build for older version of android, might not work properly. please contact developer"
> Meterpreter sessions continues to open and close.
> i am unable to execute any command.

Same error I get and I need help : (

**Comment by hiime** [comment]
> > while using msfvenom, it works fine for android version 7.0
> > But when i am installing it in android 10, it says" this app is build for older version of android, might not work properly. please contact developer"
> > Meterpreter sessions continues to open and close.
> > i am unable to execute any command.
> 
> Same error I get and I need help : (

Can I contect with u my gmail rakeshdudy38@gmail.com

**Comment by Morsmalleo** [comment]
TheFatRat will become unstable as android versions grow, its a lot like AhMyth Android RAT, thats very unstable on newer android versions and newer app versions, TheFatRat has a lot more android support and can backdoor applications that run on android 9 both rooted and non-rooted, but for android 10 I would imagine that something need to be integrated into TheFatRat in order to support backdooring Android 10 apps that will in return run smoothly on android 10 devices returning you a meterpreter session or whichever remote access option you chose with TheFatRat

**Comment by Morsmalleo** [comment]
Another thing people might try, if you are using virtual machines then set your network type to "Bridged Adapter"

**Comment by pranshushakya123** [comment]
I am facing the same issue with windows backdoor??
There is not reverse connection back after running the backdoor on target computer

**Comment by 4445MB** [comment]
hack has been improve if you know what i mean ,hack is down locally

**Comment by DivyanshTiwari20** [comment]
> backdoored apk's wont work with the "Backdoor Apk" option just above "the old fatrat method" (option 2), only on some older APK files it will work, due to the backdoor apk option being outdated (broken) as explained in another FatRat issue by @peterpt
> 
> however when choosing the option 1 to create a standalone msfvenom payload, it works fine, and if using a virtual machine make sure you have bridged adapters enabled, otherwise the payload wont connect back to the meterpreter session after being installed and opened on the victim phone

hi bro i am also having trouble in fatrat i choose the (option1) everything goes perfect but at the last my meterpreter session didn't showing me anything can you tell me how i can enable bridged adapters **(may be my issue resolve)**

**Comment by villaceran** [comment]
For now 2025 apk don't work any Android 14
