### ISSUE TITLE
FatRat not working

### ISSUE THREAD

**Issue by Stikey-1** [screetsec/TheFatRat#437]
Hello,

I’m trying to create a backdoor with option 5 in fat rat main menu.
Everything goes perfect, I insert my public ip (cause I want it to work over wan) I set up my port (which is correctly port-forwarded, even checked on canyouseeme.org), the problem is: Once msf starts and I set up the listener (my private ip and the same port of the payload config) I open the backdoor on the device and nothing happen.
Who can explain this? This is really frustrating, every other payload works perfecly... (I’m using a meterpreter_tcp payload)

**Comment by peterpt** [comment]
meterpreter_tcp does not work for what you want , it must be meterpreter/reverse_tcp , so the target computer can reverse to you .
Also some payloads take more time to bypass windows protections and if an firewall on the target computer is working then you will probably will have no luck at all because your selected remove port will be blocked .

**Comment by 13eeCoder** [comment]
Yes i made using option 2-->2 listening with msfconsole for windows/meterpreter/reverse_tcp doesnt work nothing is received even after closing firewalll and antivirus + allowing specific ports
