### ISSUE TITLE
[x] There was an error creating your FUD rat with Powerstager . 

### ISSUE THREAD

**Issue by random-guy-exe** [Screetsec/TheFatRat#460]

**Comment by FabxBs** [comment]
I can confirm this issue, same thing happened to me on kali 2020.x

**Comment by peterpt** [comment]
The problem is that powerstager is not maintained anymore by its creator , and for it to work you have to install the versions of mingw32 & 64bit from debian jessie repositories witch is not available in your current kali repositories .
You have to comment your lines from kali rooling in your sources.list and add the debian jessie repositories to sources.list , then remove your current mingw versions and install the lower versions from jessie .
look here https://github.com/Screetsec/TheFatRat/issues/391

**Comment by peterpt** [comment]
I will probably create a mingw version script fix to fix your versions of mingw in fatrat
.
powerstager requires 4.9.1 version of mingw and kali it is already in 9.x version

to fix this issue you should do this way :

1st - add this line to /etc/apt/sources.list
**deb deb http://ftp.debian.org/debian jessie main**

2nd - remove all your mingw versions , write  this in your terminal
**apt-get remove --purge *mingw* -y && apt-get autoremove -y**

3rd - update your repositories and install mingw from jessie
**apt-get update && apt-get install -t jessie *mingw* -f -y**

Powerstager will work now without any issues because it have the correct version 4.9.1
