### ISSUE TITLE
File created doesn't work  

### ISSUE THREAD

**Issue by jennaAz** [Screetsec/TheFatRat#471]
I have been trying to work with the fat rat since a while. I am not a programmer but I have a lot of will to learn. Anyhow, I followed many tutorials and it never worked. I meen, TheFatRat work properly, create a file, but when I transfer the file in my windows 10 virtualbox and try to run it as administrator, while at the same time, listenning with metasploit install on a vps, the file run on the windows 10 side and seem to crash right away, and on the vps-metasploit side, nothing is received. 
[*] Started reverse TCP handler on xxx.xxx.xx.xxx:xxxx

I use   Manjaro-Black Arch as my regular computer with the fat rat install on it version 1.9.7  
I run a vps in arch for metasploit v5.0.81-dev  
I use a virtualbox with Windows 10 as a target. (setup in bridge adapter for network setting)

I tried various types of payloads, different settings. I use the IP of my VPS as a local IP without port forwarding. I also disabled the firewall in my windows virtualbox...
I could send more details if needed. I would really appreciate some help with this

**Comment by peterpt** [comment]
payloads do not work 100% from fatrat , more higher version of windows then less chance of success you will have .
Fatrat worked perfectly at the beginning of the release but people started to send the payloads to virustotal for analysis  and then then windows defender started to detect and block it .
Also if you create a 64bit payload to run in a 32bit system then it will crash because of the architecture .
On a new recently installed windows payloads should work , but after windows updates most of them do not work .

**Comment by jennaAz** [comment]
Tell me. In Fat Rat, witch payload work better from your opinion? for wich systems? Apk for androids? exe for older versions of windows? doc? bat? 
Thanks a lot to taje the time to respond
