### ISSUE TITLE
Everything Showing Fine While Installing Fatrat But not working

### ISSUE THREAD

**Issue by Deepakk8510** [screetsec/TheFatRat#476]
chk_tools showing these problem. kindly help me.
![Screenshot 2020-05-08 18:24:53](https://user-images.githubusercontent.com/65010068/81383231-5000b180-912d-11ea-8357-e97cd7d4ed0c.png)

**Comment by peterpt** [comment]
the help is there , you just have to follow the instructions

**Comment by Deepakk8510** [comment]
Unable to install Mingw32 or mingw-w64
when i try this command i got this return(refer SS)
![Screenshot 2020-05-09 20:07:20](https://user-images.githubusercontent.com/65010068/81469551-24e89180-9203-11ea-9cde-bfb3de74d5f3.png)

apt-get update && apt-get install -t jessie *mingw* -f -y
See source.list also
Kindly help me.

**Comment by peterpt** [comment]
do you see any # behind the line showed in chk_tools script ?
So , why did you place it in your sources.list file ?

**Comment by Deepakk8510** [comment]
So I have to remove # form lines???

**Comment by peterpt** [comment]
no , only lines started with deb

**Comment by Deepakk8510** [comment]
I removed # from lines now i am getting this error.
![Screenshot 2020-05-10 02:59:27](https://user-images.githubusercontent.com/65010068/81478654-634e7280-923c-11ea-852a-d2cf00d42dae.png)

**Comment by Deepakk8510** [comment]
showing this now...kindly help
![Screenshot 2020-05-10 03:35:22](https://user-images.githubusercontent.com/65010068/81479497-3e103300-9241-11ea-9f1f-85fd15418bd1.png)

**Comment by peterpt** [comment]
leave only 1 source link in sources.list  .
Jesus Christ !!!! Did you started to use linux yesterday ?!!!!
_I dont have patience to explain all the basic stuff that a normal user should know in linux !!!

1st - leave only the source link that the script provided  without the cardinal # sources.list 
then write this :

apt-get clean && apt-get clean cache && apt-get update && apt-get autoremove -y 

then after that point run apt-get install -t jessie *mingw* -y

in case fails then use aptitude instead of apt-get , like this : 
aptitude install -t jessie *mingw*

**Comment by Deepakk8510** [comment]
Please i request please help me.
i followed your above post and first use this command
apt-get clean && apt-get clean cache && apt-get update && apt-get autoremove -y
then i tried (apt-get install -t jessie *mingw* -y) but at last this error showing.


![Screenshot 2020-05-10 05:06:59](https://user-images.githubusercontent.com/65010068/81481520-6c483f80-924e-11ea-9d71-d935df1fb2ac.png)
The following packages have unmet dependencies:
 gdb-mingw-w64 : Depends: gdb (>= 7.6.2)
                 Depends: libpython2.7 (>= 2.7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Deepakk8510** [comment]
Please help me i am waiting for your help

**Comment by peterpt** [comment]
use aptitude 

aptitude install \*mingw\*

**Comment by peterpt** [comment]
apt-get upgrade -y && apt-get dist-upgrade -y && apt-get install *mingw*

**Comment by Deepakk8510** [comment]
not working same error....should i give up???

**Comment by peterpt** [comment]
Yup , probably is the thing to do is give up because to use this tool you should have a minimum knowledge in linux in how to install packages and fix them , and i dont have patience to stay in this threat 100 times for an error outside of fatrat scope .
Issues should be  created when there is a error in the code of fatrat .
