### ISSUE TITLE
Unable to locate package <package name>

### ISSUE THREAD

**Issue by lylest** [Screetsec/TheFatRat#480]
i got this error when trying to install the missing packages when i runned setup.sh script
`Backdoor-factory -> Not OK                                                                                                                                            
Searchsploit -> OK                                                                                                                                                    
Was not possible to install The Packages Labeled (Not Ok) in this list above                                                                                          
Try : (apt-get remove --purge <packagename> && apt-get autoremove && apt-get install -f)                                                                              
before running fatrat setup script again                                                                                                                              
root@fsociety:/home/fsociety/bytes/TheFatRat# apt-get install gnome-terminal                                                                               
Reading package lists... Done                                                                                                                                         
Building dependency tree                                                                                                                                              
Reading state information... Done                                                                                                                                     
E: Unable to locate package gnome-terminal `

**Comment by peterpt** [comment]
2 options , install using kali repository , or clone the backdoor factory git and select manual path when setup prompts for its location

**Comment by lylest** [comment]
Give me the link to the Kali Linux repo and how big is it

**Comment by peterpt** [comment]
https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/

**Comment by lylest** [comment]
It seems like it got something to do with sources.list file I was
asking for a favour can you please send us the recommended sample of
sources.list file or the one which you use
You can even write one which will work in most cases based on your
experience
That will help not just me but the world I have seen lots of people
suffering from this issue
 Thank you in advance

**Comment by peterpt** [comment]
Look , my will is to remove setup.sh and program fatrat to tell user witch packages are missing , and then the user will have to deal with them , however Edo from the beginning created setup for very noob people that just installed linux but dont have an idea how it works its principles , of course that will lead to issues along the way because not everyone uses the same linux distribution and because 50% of the people dont have any repository activated in their sources list file , this will mean that user will never be able to update their linux distribution to future vulnerabilities .
Some linux distributions come with at leat one line activated in sources.list , others have only the original cdrom as repository .
By default fatrat add 2 repositories to sources.list of user to be able to install most of the packages , one of them is the kali repository , so when you run setup it means that when that script is running you have kali repository activated .
All you have to do is when backdoor factory pops up select the option "Install from kali repository" , and setup will do it for you .

**Comment by lylest** [comment]
I tried yesterday lots of things I like 5 issues with all of the solutions
I saw you  have answer most of the questions 🔥 you did a great job but
none of them worked I  even accidentally unistalled apt packege

**Comment by peterpt** [comment]
upload apt.log from fatrat/logs  folder to here

**Comment by lylest** [comment]
I'll try and I will let you know
 And sir can you please give me your email I would like to have a talk with
you

**Comment by peterpt** [comment]
nop , no emails  , just upload here the apt.log

**Comment by lylest** [comment]
It worked thank you but it only works on my Android phone when I tried to
another  phone it doesn't work
Why is that
Is it because I am using the same internet connection with my computer?
Because I have hospoted my PC to my phone

**Comment by ghost** [comment]
How can I fix the unable to find package on termux
