### ISSUE TITLE
Infinite "Checking for internet connection"

### ISSUE THREAD

**Issue by gfonzy96** [screetsec/TheFatRat#481]
After running setup.sh it detects my OS and local shell then gets stuck on checking for internet connection. I can ping google with 0% packet loss, and have had no internet issues since installing Linux Mint Cinnamon 19.3, and there doesn't seem to be any error reports generated by the setup in the directory that it specifies.

Edit: Yes i have netcat installed.

![Screenshot from 2020-05-20 00-18-07](https://user-images.githubusercontent.com/65197117/82407681-6bbe5e80-9a2f-11ea-9c5d-0aafd1018a61.png)
OS:  Linux Mint 19.3 Cinnamon
Cinnamon Version: 4.4.8
Linux Kernel: 5.3.0-51-generic
Processor: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx x 2
Memory 5.8 GiB
Hard Drives: 275.7 GiB

**Comment by peterpt** [comment]
netcat connects to google.com on port 80 , in case you are not connected to internet or if your isp is blocking google then that situation may happen

**Comment by gfonzy96** [comment]
My ISP is not blocking google, and I can ping google with 0% packet loss from terminal, wifi settings all look good, no issues anywhere else or with any other tools. Metasploit framework has no issues connecting or creating meterpreters either if that is relevant.

**Comment by peterpt** [comment]
tell me what happens if you write in terminal this :
echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80

**Comment by gfonzy96** [comment]
> tell me what happens if you write in terminal this :
> echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80

Nothing at all happens. Output is just infinitely blank. If this means it isn't an issue with TheFatRat, but instead an issue on my end, could you give me a resource or keyword for me to search to fix before closing? Thank you.

**Comment by peterpt** [comment]
This is what output should be from that command :

![nc](https://user-images.githubusercontent.com/7487321/82584320-dda7bc80-9b83-11ea-9e8f-5dea3cd890a0.jpg)


So , probably is some king of network gateway bad config in your system or anything else .

**Comment by gfonzy96** [comment]
> This is what output should be from that command :
> 
> ![nc](https://user-images.githubusercontent.com/7487321/82584320-dda7bc80-9b83-11ea-9e8f-5dea3cd890a0.jpg)
> 
> So , probably is some kind of network gateway bad config in your system or anything else .

You're probably right, and while I was waiting for your reply, I ran a few netcat scans, everything worked fine, and configured google's open DNS 8.8.8.8 and 8.8.4.4 in my network setting, but still am not having any luck, and I have no clue where to even begin trouble shooting this issue considering I have no idea what is configured incorrectly or where to start looking in the first place? Any direction you can point me in for further help?

**Comment by peterpt** [comment]
try downgrading netcat version .
I have no idea why your netcat is not working .

**Comment by peterpt** [comment]
I Installed netcat 1.10-41.1 from kali repository and everything works fine , so probably the problem is dns resolution on your system is not ok , what this means is that you can do whatever you want with netcat as long as you use an ip address in it , when you write an hostname then netcat is unable to resolve the hostname to an ip , and this is probably why it stays hanged .
Some people here also have the same issue with ping command .

Maybe you can solve the issue by editing the file "interfaces" in /etc/network/interfaces 
and configure it to a static ip address and then add manually your name servers , no mather if it is google or opendns  .
I have no idea how kali 2020 firewall is configured because from kali i only have the kernel and headers installed in my system so i dont give the trouble myself to patch the wireless drivers , all other stuff here is devuan .
But to check firewall just write "iptables -L" in terminal
it should bring all the rules configured in the firewall , when input forward and output policies should be "ACCEPT" , in case not then write "iptables -F" to flush all rules from firewall .
