### ISSUE TITLE
 [!] Failed to recompile original project with backdoor

### ISSUE THREAD

**Issue by hichemkanon** [screetsec/TheFatRat#507]
hello guys ! i have problem when binding payload into """any""" apk i get this message error "
[!] Failed to recompile original project with backdoor" 
any solutions ?????
i have replaced the apktool and apktool.jar then i get same error, plz help

**Comment by peterpt** [comment]
And why did you replaced the apktool ?
the current apk tool in fatrat is the latest .
Apk binder is not 100% reliable , and the script that builds it is at :
https://github.com/dana-at-cp/backdoor-apk

Download the original script and test it , if original script gives you an error then fatrat will also do.

**Comment by martinssssssss** [comment]
Hello, do you have a solution to this problem?

**Comment by peterpt** [comment]
Believe it or not the most problem with that error is related to apktool , after a few tests here i realized that if you decompile an apk with apktool and if you recompile it right again with apktool without any error then if you use that original apk in fatrat it will work .
The problem is that sometimes apktool is not able to recompile again the apk even if no changes were made in the code .
