### ISSUE TITLE
Linux mint

### ISSUE THREAD

**Issue by dinoarg** [Screetsec/TheFatRat#51]
Hi, 

When i try to install ./setup.sh it's ok, but i cant install "mingw32".

terminal show me "mingw32 compiler  -> not found ".

how can i do? 

------

   ____ _               _    _                   
  / ___| |__   ___  ___| | _(_)_ __   __ _             
 | |   | '_ \ / _ \/ __| |/ / | '_ \ / _\ |            
 | |___| | | |  __/ (__|   <| | | | | (_| |  _   _   _ 
  \____|_| |_|\___|\___|_|\_\_|_| |_|\__/ | (_) (_) (_)
                                     	|___/    
-- -- +=[(c) 2016-2017 | dracos-linux.org | Linuxsec.org | Hacker Indonesia 
-- -- +=[ Author: Screetsec < Edo Maland >  ]=+ -- -- 
 
[!]::[Check Dependencies]:
[✔]::[Distro]: Linux
[✔]::[Check User]: root
[✔]::[Internet Connection]: connected!
[✔]::[Apache2 Server Linux ]: installation found!
[✔]::[Msfconsole]: installation found!
[✔]::[Msfvenom]: installation found!
[✔]::[Zenity]: installation found!
[x]::[warning]:this script require mingw32 installed to work

[!]::Run setup.sh to install ming32

i run setup.sh blablablabla, but not ming32 not get

**Comment by peterpt** [comment]
from distro to distro , packages have different names .
try : apt-get install gcc-mingw32 
then write here if it works .
The default install works on debian based distros , and in debian based distros te package is called mingw32 .

We do not install that package with kali repositories because it may get issues with your current distribution .

Next time something like this happen , try first : apt-cache search mingw32

https://community.linuxmint.com/software/view/gcc-mingw32

**Comment by dinoarg** [comment]
that not work for me, i virtalize kali on VB and install thefatrat, i have the same issue bat i agree some repositories and did work, i dont know whathappend with linux mint, but it's okey on kali.

**Comment by peterpt** [comment]
very confusing your  response .
" i virtalize kali on VB and install thefatrat, i have the same issue"
Does this mean that you create a Virtual Machine with Kali OS and did not worked  ?

" i dont know whathappend with linux mint"
Mint have different packages names in repositories , for now , fatrat will work (install) fine on debian based distributions like Devuan , Debian , Kali , Ubuntu that use same debian package names repositories .
However we have plans to adapt it to others distros like Mint , Arch , etc...
One of the issues is that package names change name from distribution to distribution , and when setup call some package from your current OS repository to install and that package does not exist , then you will be stuck in that package and fatrat will not work . 

" but it's okey on kali."
Explain this part , on Virtual machine , the instalation did not worked ?! and on non Virtual Machine worked ?

Note  : write slowly and with time , so i can understand what is happening there .

**Comment by dinoarg** [comment]
I'm sorry about last answer, i take the neccesary time.

In linux mint it's still not working beacause the problem are the repo of mingw32, exactly what you say, fatrat will work distributions of debian.

However, i take Virtualbox and i install Kali linux x64. Then i clone the repo "git clone xxxxxx" and i install the fat rat. 

At the first i had the same problem wich i have with linux mint, i cant install mingw32, so, i check in all internet and i found the solution, to fat rat works on kali. 

i modify the file ./etc/apt/source.list and i add this next's repos:

deb http://http.kali.org/kali sana main non-free contrib
deb-src http://http.kali.org/kali sana main non-free contrib
deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb http://ftp.de.debian.org/debian jessie main

apt-get update 

and 

apt-get install mingw32 

and it's work.

**Comment by peterpt** [comment]
we did not made mingw32 instalation with kali repositories because your OS may get some packages conflicts with the kali repository .

The reason is that some packages needed in fatrat , when you install them , they install all their dependencies , libraries and etc .. 
If we use kali repo to install everything in setup , then you Linux may get conflicting packages on other programs and they may not work .

anyway , you forgot to write here the output of the command i wrote before : 

write this command in your terminal : 
awk '{print $1}' /etc/issue

and post here the output .

**Comment by dinoarg** [comment]
the output is: 

dino@t430 ~ $ awk '{print $1}' /etc/issue
Linux


i understand what you say. That output it's printed on my linux mint. At this time, i happy to fatrat work in my kali on Virtualbox

**Comment by peterpt** [comment]
sorry to ask you again , but write now this command   
awk '{print $2}' /etc/issue

and post here the result .

the reason i am asking this , is for in future we detect automatically with OS distribution the user is using , and adapt the correct repositories list to setup script .

**Comment by dinoarg** [comment]
dino@t430 ~ $ awk '{print $2}' /etc/issue
Mint

i like participate in that project.

**Comment by peterpt** [comment]
Thanks for the reply on this one .
We may in future create a detection of Linux distro by getting OS name using a similar instruction like you did and then make setup to adjust packages to that specific distribution .

For your knowledge , the command you wrote that gave you "Mint" output was , reading the second word for your file in /etc/issue .

if you write on your terminal "cat /etc/issue" , you will get:
Linux Mint ......
...= and other stuff

**Comment by dinoarg** [comment]
yeah u right. well if u team or you need help, just send me PM.

cheers and thank 4 ur help

**Comment by peterpt** [comment]
you can always contribute if you want , like i did .
I am doing for fun because github is an opensource project where everyone collaborate with each others .
All you have to do is clone fatrat repo from  streetsec to your github , adapt the script for better and send the pull requests to streetsec main repository .
If the owner of the script like your changes and if your changes had improved the script , and if it is working perfectly as before , then he should merge your changes from your git to the main git of fatrat .
When he merges your changes to main script , your new stuff will be working on everyone that clone the main git to their hdd to run the script , or to other users .
