### ISSUE TITLE
Kali Linux fat rat payload

### ISSUE THREAD

**Issue by arjunbavan** [screetsec/TheFatRat#608]
There was an error creating your fud ray with Powerstager Iam getting this issue while creating payload in fat rat could anyone solve this issue in detail cause I’m not pro in it doing Kali Linux has a hobby

**Comment by Morsmalleo** [comment]
Delete TheFatRat completely and then type these commands into your terminal 

`git clone https://github.com/Screetsec/TheFatRat`
`cd TheFatRat`
`sudo chmod +x update chk_tools setup.sh`

If you are using an older version of python-pip then run these commands because TheFatRat now works with pip3

Run this command to install pip3
`sudo apt install pip3` 

Then run the setup with this command
`sudo ./setup.sh` 

If you have any errors with *Mingw-32* or *Mingw-w64* during setup, then run the setup file again, if the problem persists let me know

**Comment by shane89420** [comment]
I have a log in my issues that I don't know how to fix can you please help me

**Comment by arjunbavan** [comment]
Could u say how to delete it completely

**Comment by Morsmalleo** [comment]
sudo rm -rf TheFatRat

**Comment by Morsmalleo** [comment]
> Could u say how to delete it completely

Yes can delete TheFatRat fully by typing this command
`sudo rm -rf TheFatRat`
