### ISSUE TITLE
APK RAT FILE WAS NOT FOUND

### ISSUE THREAD

**Issue by anjuch** [Screetsec/TheFatRat#62]
Not saving backdoored apk file. The last lines as follows:

File copied with success to : /root/Desktop/TheFatRat-master/backdoored
Removing temporary files from output
Signing your APK file
Usage: signapk publickey.x509[.pem] privatekey.pk8 input.jar output.jar
[!] APK Rat file was not found in : /root/Desktop/TheFatRat-master/backdoored/output/

**Comment by peterpt** [comment]
The APK file is sgined 2 times , the first time is signed when after it is merged , then it is signed again with the current certificate inside tools folder .
I already notice this problem is some apks before , where it pops up an error when is trying to sign the apk for the 2nd time using fatrat creator certificates , but i never changed that code because the original code is not mine , and i have no idea if the fatrat creator wants that second signing apk code removed .
However , you should have in your  /root/Desktop/TheFatRat-master/backdoored/ the current apk created , or check in  /root/Desktop/TheFatRat-master/ directory .
