### ISSUE TITLE
i cant find command to run the fat rat

### ISSUE THREAD

**Issue by LilCyro** [screetsec/TheFatRat#664]
i have installed fat rat in kali but idfk how to run it : /

**Comment by raeraer** [comment]
The comand its fatrat. Im not sure, but in the end of the instalation, when asked if you want a shortcut of fatrat, i guess its also asked if you want to be able to call it from terminal. Try reinstaling and check those last questions.
Its also possible that you didnt finished the instalation, due to not having all dependencies instaled. Some of the dependencies i had to install myself.
