### ISSUE TITLE
Fat-rats's payloads are too old ? Is possible to bypass Play store protect Alert ?

### ISSUE THREAD

**Issue by legilimency31** [screetsec/TheFatRat#665]
The reverse tcp payload embeded into an original app sucefully is still being alerted on the android target by Google play Protect. Is there a way to bypass it ? Or it means the payloads used by fat-rat are too old ?

**Comment by Morsmalleo** [comment]
> The reverse tcp payload embeded into an original app sucefully is still being alerted on the android target by Google play Protect. Is there a way to bypass it ? Or it means the payloads used by fat-rat are too old ?

Reverse TCP payload have been detectable on Android for years, if you want a FUD payload then you need to use powerstager or slow but powerful, but these only build windows executables I think

**Comment by raeraer** [comment]
> `Powerstager`

So what you are saying is that every (or most ?) reverse tcp payloads for android can not bypass google play protect, due to its own fundamental structure ? So its not a matter of being new or old ? Their type itself is easily detectable ?
 
What i found very curious is that a reverse tcp payload apk, not embebed in any original app,  instaled in my lolipop android didnt caused the google play protect alert. But when i embebed it into an original app, the alert happened.

**Comment by raeraer** [comment]
> > The reverse tcp payload embeded into an original app sucefully is still being alerted on the android target by Google play Protect. Is there a way to bypass it ? Or it means the payloads used by fat-rat are too old ?
> 
> Reverse TCP payload have been detectable on Android for years, if you want a FUD payload then you need to use `Powerstager` or `Slow But Powerful`, but these only build windows executables I think, but they're FUD I can't tell you that right now

So what you are saying is that every (or most ?) reverse tcp payloads for android can not bypass google play protect, due to its own fundamental structure ? So its not a matter of being new or old ? Their type itself is easily detectable ?

What i found very curious is that a reverse tcp payload apk, not embebed in any original app, instaled in my lolipop android didnt caused the google play protect alert. But when i embebed it into an original app, the alert happened.

**Comment by Morsmalleo** [comment]
> > > The reverse tcp payload embeded into an original app sucefully is still being alerted on the android target by Google play Protect. Is there a way to bypass it ? Or it means the payloads used by fat-rat are too old ?
> > 
> > 
> > Reverse TCP payload have been detectable on Android for years, if you want a FUD payload then you need to use `Powerstager` or `Slow But Powerful`, but these only build windows executables I think, but they're FUD I can't tell you that right now
> 
> So what you are saying is that every (or most ?) reverse tcp payloads for android can not bypass google play protect, due to its own fundamental structure ? So its not a matter of being new or old ? Their type itself is easily detectable ?
> 
> What i found very curious is that a reverse tcp payload apk, not embebed in any original app, instaled in my lolipop android didnt caused the google play protect alert. But when i embebed it into an original app, the alert happened.

Yes that's exactly what I am saying, as for your Lollipop android that's an older version of android this version of android wasn't protected against reverse TCP payloads, now in saying that, many versions of Android after Lollipop, were protected against reverse TCP payloads in the form of play protect or virus scanners however they are still able to run if they are opened, but they won't be opened because they're easily detectable, however if you use the encryption protocols with msfvenom you may find you can bypass some AV's

**Comment by Morsmalleo** [comment]
Most of these detections are thanks to idiotic morons who think they're computer professionals by uploading files built by educational tools such as TheFatRat or AhMyth, to `VirusTotal` when `NoDistribute` is the way to go when dealing with educational tools like this.

**Comment by raeraer** [comment]
> Most of these detections are thanks to idiotic morons who think they're computer professionals by uploading files built by educational tools such as TheFatRat or AhMyth, to `VirusTotal`, when `NoDistribute` is the way to go when analysing files built by educational tools like this.
> 
> Now in saying that I am not saying that VirusTotal is useless, because it's not! VirusTotal has armed Windows Defender on many PC's across the globe with many needed protections against things such as Ransomware, so VirusTotal is great, but when it comes to files built by educational tools such as TheFatRat or AhMyth, they need to be uploaded to NoDistribute, simply because they're files built from an `OPEN SOURCE` tool that's available to everyone with a github account, why is it open source? Because it's educational, it's meant to give those who are just starting in the area of penetration testing a step in the right direction.

That make sense. Android fud payloads seems to be a lot rarer then fud for windows. FatRat itself, and many other similar tools that i tested,  have fud payloads for windows, but never for android. Do you know why ? And have any suggestions on similar tools with fud payload for android ?
By the way, thanks for answering me, im learning a lot.

**Comment by peterpt** [comment]
All payloads in fatrat for android are generated by metasploit framework .

**Comment by martdev123** [comment]
This is for educational purpose so it's ok to be open source indeed
