### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by muhammadqazi** [screetsec/TheFatRat#674]
I am trying to use FATRAT but it stucks in middle of installation process
![Screenshot from 2022-01-27 21-21-43](https://user-images.githubusercontent.com/86423826/151429290-42252e5f-51fa-4283-93be-3ee94d01ace2.png)
.

**Comment by peterpt** [comment]
Thanks , i am checking it out here with a fresh installation of kali , however in my system witch is devuan i tested without issues .
Keep in mind that kali repositories take a while to update , so try to wait a bit to see what happens because if it was an error then it showed up on your screen .
In mean while i will do some tests here and will correct in case if that stuck happens .

**Comment by peterpt** [comment]
Its not stuck , the problem is that kali repositories are very slow and fatrat need to clean the apt cache from previous repository (jessie) before give an option for user to install tools from kali , (metasploit , exploitdb and backdoor-factory) .
If you look into your router lights you will see them flashing while you think setup is stuck , this is because (apt update) is running in background for repokey function , so if the pubkey for kali is missing it will correct it automatically .

**Comment by muhammadqazi** [comment]
Thanks bro, it's working
