### ISSUE TITLE
PwnWind : C# + powershell file not generated

### ISSUE THREAD

**Issue by EinderJam** [Screetsec/TheFatRat#77]
When i try to build a backdoor with this option,i don't get any file in the output folder.
The other methods work,I use kali rolling 2016.2 in a VM,with a fresh install of TheFatRat
Have you got an idea ?

**Comment by t-1559-t** [comment]
I have exactly same problem, only difference is that im running kali in live persistence.

**Comment by peterpt** [comment]
Thanks for posting this issue .
I am also having the same problem here .
I will check out where it is this bug .

**Comment by kn0wledge** [comment]
same issue

**Comment by peterpt** [comment]
According to what i can see , everyone should have this issue .
The output of the compiling was reedirected to /dev/null , to avoid a massive text entry on fatrat screen , and this is why you all only get "File saved to output folder" at the end , but in reality no file was created because there was no code between all the process of making the payload , filter the payload and compiling the payload to exe to stop in case any of these processes fail in the middle .

However , i already detected where is the error .
The error happens in  almost at the end of all the compiling process where the command "sed" should be filtering the seletcted data for the payload and insert it in the temporary file that monodenvelop will use to compile the exe file .
Because "Sed" is not doing its job correctly , then mono gives an output error that i was able to catch .
This way , error appears , process is stopped and no output is generated .
I had to made some changes in the fatrat code to get this error log .
https://s12.postimg.org/3wziirnvx/error.png

However , the error was detected but the correction of it could take some days to fix .
Will be very busy in the next month , on next weekend i will give a look into the code .

**Comment by peterpt** [comment]
This issue was fixed in latest git upgrade .
Do a git pull inside FatRat directory to update fatrat .

**Comment by EinderJam** [comment]
it works fine now,thanks !

**Comment by castanhinha1** [comment]
@peterpt I have updated to the latest version and am not generating the .exe file. I am getting Programr Saved To output/Program.cs

**Comment by tone602** [comment]
@peterpt I am also having the issue to where there is no output exe file generated. I have updated to v1.9.6 on parrot running as main OS.

**Comment by eLGROSKompadre** [comment]
the same on parrot os, anyone can help please ?

and not only with this payload, but all payloadS....

**Comment by BonelessBob** [comment]
I have the same problem on both my parrot and kali... I have no clue what causes it

**Comment by L1ghtman2k** [comment]
Same issue

**Comment by perimeterscout** [comment]
Same issue here. When I create try to create an exe file with apache + powershell I get nothing in the output folder. I've tried to remove and reinstall but to no avial. Any advice or recommendations would be appreciated.

**Comment by SehrishRiaz** [comment]
I created a backdoor using thefatrat the code in in C# encoded command. I wanna know how ca i decode the code?
