### ISSUE TITLE
fail to install aapt

### ISSUE THREAD

**Issue by gearcapitan** [Screetsec/TheFatRat#87]
![kali linux-2017-04-09-17-38-20](https://cloud.githubusercontent.com/assets/13740942/24841475/5f20e594-1d4b-11e7-822d-0cec1854ec84.png)

**Comment by peterpt** [comment]
There is no problem at all , as you can see right ahead the aapt is installed automatically next to red line .
Red line in aapt means a uninstalation of a current old version of aapt in your system .
It means that fatrat detected an aapt version and remove it .

aapt , proguard , zipalign & Dx are not installed from OS repository because they are included in fatrat package .

**Comment by Hades44** [comment]
Plz brother help me..I'm using kali nethunter am facing some problems to install fatrat..Am not able to install DX,Aapt,Apktool..
Plz brother's help me..how can I fix this problem!!
