### ISSUE TITLE
Error after instalition thefatrat

### ISSUE THREAD

**Issue by JayendJr** [Screetsec/TheFatRat#93]
hy i a newbie , please give me solution how to fix problem .
when i install thefatrat ,i have a problem about can't open other location?
please help me . how fix this problem ?

**Comment by peterpt** [comment]
Define what you call installation complete .
write step by step .
Use google to translate .

**Comment by peterpt** [comment]
Watch this video in 1 hour .
I am uploading it
https://youtu.be/qqFORedd-oE

**Comment by JayendJr** [comment]
video can not be accessed guys

**Comment by horllste** [comment]
a screen-shot of your error should be okay

**Comment by peterpt** [comment]
Do you understand english ?!!

"Watch this video in 1 hour ."
I am uploading it now .

So , maybe it is working now .
Dont regulate yourself by github timming posts , because i uploaded the video 54 minutes ago .
watch it now .

**Comment by godimdhruv** [comment]
Plz solve this issue I m using kali nethunter in yureka plus arm 64
the problem which shows on my screen after type command chmod +x setup.sh && ./setup.sh
"System will not proceed because none of the architecture are present 
X86_64 l i386 l i486 l i586 li686
Report This arch : aarch64 into fatrat issue on github
Press any key to continue"

**Comment by peterpt** [comment]
just execute on fatrat folder :  
./update

and then follow the normal procedures to install fatrat
