### ISSUE TITLE
Zenity

### ISSUE THREAD

**Issue by gremlinflat** [Screetsec/TheFatRat#96]
Can u make it full commandline.?? without zenity and some remove GUI windows for selection payload..

its make harder to generate payload on vps

**Comment by peterpt** [comment]
Removing zenity from the code will demand a lot of code to be implemented , while with zenity in 1 line you can setup 10 different options , without it will require at least 50 .
This will demand a lot of code to be implemented just for that option .

**Comment by Screetsec** [comment]
@gremlinflat  yeah i know , maybe i will discuss and think for update the features or make for vps version

**Comment by peterpt** [comment]
Well , i my point of view i consider implementing that option a lack of will or knowledge to put fatrat working on a VPS .
Instead using a remote shell , the user can start a remote desktop service on the VPS and connect to it from his station .
Removing zenity will also demand a rebuild of setup script , and that just because the user don`t have a clever idea in how to bypass the problem .

In this next image i connected to other server i have using a remote desktop from windows and it works perfectly . 
https://s22.postimg.org/4awrbioyp/rdesktopfatrat.jpg

Changing the whole structure of the tool just because 1 user have problems makes no sense at all .
It is better to explain the multiples options to user how can he make it work , instead spending days recoding the scripts again .
