### ISSUE TITLE
Error :- require mingw32

### ISSUE THREAD

**Issue by vikas-chhabra** [Screetsec/TheFatRat#98]
after installing fatrat i got an error i.e. mingw32 required. 
i have tried reinstalling fatrat
i have tried to update my repo and "apt-get install mingw32"
i have also tried wine to install mingw32 but failed

PLEASE HELP
THANK  YOU!!!

**Comment by peterpt** [comment]
yes , you are right , the force option is missing on mingw32 installation on setup.sh script .

Only eldo can do that change now in setup.sh script , my git of fatrat is so far ahead that even if i explain to you how to get my setup.sh script and execute it , it wont work on screetsec git push on your hdd because my fatrat tools directory are different and would popup errors executing fatrat .

Anyway , for that to happen then you are not in kali OS , you are using a different debian distribution .

**Comment by peterpt** [comment]
With a text editor like "leafpad" open setup.sh file and make the changes like there is in the next image .

https://s9.postimg.org/wdrp93qfz/change.jpg

then execute ./setup.sh again and everything will be fine .

**Comment by vikas-chhabra** [comment]
thank you so much for your help!!!
Let me try

**Comment by peterpt** [comment]
Edo , your fatrat git will have issues with my setup.sh only .
The reason is that i changed all my tools directory structure and in your git it is in old directory structure .

Ex : I have android-sdk
you have  android-sdk-25.0.2

I install dex2jar directly on user system from tools folder , while in your git you install it from kali repo .

Expect a lot of issues in next 2 days for new cloners .

**Comment by Screetsec** [comment]
@peterpt  check email

**Comment by vikas-chhabra** [comment]
@peterpt not worked for me

**Comment by peterpt** [comment]
you have to execute setup.sh , do not try to install it directly from your terminal because will not work

**Comment by peterpt** [comment]
vikas-chhabra , remove your current fatrat folder , and clone again because fatrat was just updated .

**Comment by shanmnukh** [comment]
I got error in installation because of jarsigner
How to solve that plz help me

**Comment by peterpt** [comment]
create a new issue for your problem .
